### ISSUE TITLE
Community chatroom

### ISSUE THREAD

**Issue by PureTryOut** [iceiix/stevenarella#109]
First of all, thanks for picking up development of Steven! I love to have a fully open-source Minecraft client written in a proper native language like Rust.

I was wondering, would you be interested in having some community chatroom? Most "gamers" nowadays tend to go to platforms like Discord, but I'd prefer Matrix or even IRC myself. A chatroom like this would be a nice place for people to gather and discuss development, or just ask questions. It could be a good start towards a bigger developer community.

**Comment by iceiix** [comment]
Hey thanks for your interest! Glad to see I'm not the only one who wants to make this project happen :)

An IRC chat room sounds like a good idea. thinkofname used SpigotMC IRC (irc.spi.gt), but it seems EsperNet (irc.esper.net) is more popular with modding communities. I've created a channel there, #stevenarella @ irc.esper.net, but am having some trouble registering it (still waiting for the nickserv email).

To do: add IRC channel to readme

**Comment by PureTryOut** [comment]
The Matrix address for that room is [#\_espernet\_#stevenarella:matrix.org](https://matrix.to/#/#_espernet_#stevenarella:matrix.org), please add that to the README too :wink:
