### ISSUE TITLE
panicked at 'unsupported command node parser minecraft:entity_summon'

### ISSUE THREAD

**Issue by Corxam** [iceiix/stevenarella#119]
thread '<unnamed>' panicked at 'unsupported command node parser minecraft:entity_summon', src\protocol\packet.rs:2713:22
stack backtrace:
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: <unknown>
  14: <unknown>
  15: <unknown>
  16: <unknown>
  17: BaseThreadInitThunk
  18: RtlUserThreadStart

**Comment by iceiix** [comment]
https://github.com/iceiix/stevenarella/blob/0d5c1478a5e9355f40817c3ff1f6149e4b539568/src/protocol/packet.rs#L2713 impl Serializable for CommandNode fn read_from Some(match parse.as_ref() {

Missing from https://wiki.vg/Command_Data - looks like it needs to be added - but https://github.com/SpigotMC/BungeeCord/blob/4428409d41acef5495c6d41c9640c99dbb0d6468/protocol/src/main/java/net/md_5/bungee/protocol/packet/Commands.java#L514 does have minecraft:entity_summon. This is a void type, so should be easy to add.
