### ISSUE TITLE
Split out protocol support into a separate crate?

### ISSUE THREAD

**Issue by iceiix** [iceiix/stevenarella#167]
#18 (and others) added a ton of protocols, supporting multiple at once, a fairly unique and strong feature of this project. Currently implemented in src/protocol, but it could be useful to separate it out on its own crate so it can be used independently.

Example use case: creating command-line clients, proxies, or otherwise testing or debugging the protocol, without the full-blown GUI or graphics. Inspiration: https://wiki.vg/Client_List lists https://github.com/Tnze/go-mc/ "Create Minecraft bots with golang" as one of the few active clients for 1.14.1.  There are some on https://crates.io/search?q=minecraft but they are either old/obsolete, or only support one protocol version:

multi protocol:

* https://github.com/iceiix/stevenarella/tree/master/src/protocol

single protocol:

* https://crates.io/crates/acacia_net 0.1.0 - 6 months ago, protocol 404 (1.13.2)
* https://crates.io/crates/ozelot 0.8.0 - 6 months ago, protocol 404 (1.13.2)

inactive?

* https://crates.io/crates/minecraft 0.0.0 - 3 years ago
* https://crates.io/crates/rusted_minecraft 0.0.0 - 3 years ago
* https://crates.io/crates/netherrack 0.0.1 - 3 years ago
* https://crates.io/crates/montar 0.1.0 - 1 year ago
* https://crates.io/crates/hematite_server 0.0.4 - 1 year ago
* https://crates.io/crates/minor 0.1.2 - 2 years ago and GitLab link is private
* https://crates.io/crates/blacklung - yanked

support (not full protocol):

* varint
  * https://crates.io/crates/mc-varint 0.1.1
  * https://crates.io/crates/nom-varint 0.1.0
* nbt
  * https://crates.io/crates/hematite-nbt - 0.4.0
  * https://crates.io/crates/raw-nbt 0.1.1
  * https://crates.io/crates/nobility 0.1.0
  * https://crates.io/crates/nbt-parser 1.0.0
* rcon
  * https://crates.io/crates/rcon 0.1.0
* ping
  * https://crates.io/crates/craftping 0.1.0
* server wrapper
  * https://crates.io/crates/lazy-pregen 0.1.4

clients/tools:

* https://crates.io/crates/hematite 0.0.34 - 4 months ago
* https://crates.io/crates/hematite-client - deprecated in favor of hematite
* https://github.com/iceiix/stevenarella/ - 1.7.10-1.14.1

**Comment by iceiix** [comment]
On IRC someone was asking about this, so may be worth continuing #167 - although it is a lot of changes, would it be better to instead add a crate option to allow compiling out the GUI? Having a separate crate on the other hand would be nice for maintenance purposes and reuse (Alxly on IRC was interested in this project as an alternative to https://github.com/PrismarineJS/minecraft-data - which was considering a Rust wrapper: https://github.com/PrismarineJS/minecraft-data/issues/35 - they have more protocol support, but abstracted away further than us).

**Comment by DarkWeird** [comment]
@iceiix, minecraft-data use [protodef format](https://github.com/ProtoDef-io/ProtoDef) for describe data.  Code generators for elixir and nodeJs only.

**Comment by cheako** [comment]
There is feather's feather-core, but it's limited to 1.13.2/404 currently and has *unimplemented client only bindings.  I was looking at stevenarella to see if I could see how to correctly format EncryptionResponce, but I couldn't just connect it to  locally running server without knowing how.

Here is a trace from feather-server https://pastebin.com/4uMVsQin I don't know why this doesn't work.

* This is an easy fix though: https://github.com/caelunshun/feather/pull/124

**Comment by iceiix** [comment]
It would be cool to work with feather-rs to have a shared protocol crate both projects (and any others) could use, if they are interested. With extensive tests and version support. Not sure how difficult this would be.

**Comment by caelunshun** [comment]
(I'm the Feather maintainer.)

We do plan to implement multi-protocol support in feather-core after some time. There's a few difficulties with splitting the protocol into a separate crate, though—notably, types like the chunk structure are parsed into Feather's chunk implementation, which then in turn depends on our `Block` enum. As a result, any crates wanting to use the protocol crate would have to use these types as well. 

A possible solution to this would be to have users provide a function which converts protocol data for a chunk (palette and data array) into their desired type.

**Comment by cheako** [comment]
Storage for chunk data is something the feather-core crate might make flexible.  I was thinking about this when filling in the client protocol bits, that a server and client have incompatible needs as far as storing chunk data.

**Comment by queer** [comment]
Checking in as someone else who would be interested in this. I could honestly accept the ability to just add Stevenarella as a lib as a temporary hack - or something similar to that, I just want to avoid having to copy-and-paste and mangle the code myself - but I also don't have any particularly complicated needs. I know wrappers for other languages (ex. prismarinejs) exist, but having multi-protocol in one lib + being able to use it from any language that supports loading natives is something I would be very interested in.

**Comment by iceiix** [comment]
Finally got around to this, with #277 and #278, the new crate is steven_protocol. Not yet released on cargo (#280), @queer you could try depending on steven_protocol using a git dependency for now, let me know of any feedback. Note it doesn't have everything needed to develop a client, but at least includes packet decoding for various protocol versions.

**Comment by queer** [comment]
@iceiix Sweet, I’ll check it out soon! Thank you so much!
