### ISSUE TITLE
wasm broken: failed to resolve: could not find `Context` in `platform_impl`

### ISSUE THREAD

**Issue by iceiix** [iceiix/stevenarella#171]
After fixing #115 #166 std::fs (continuing #92 wasm), a new problem arises: glutin/winit doesn't support the web yet:

<details>
<summary>inline417.js:3 Panic error message: not yet implemented: Glutin-Blank: Platform unsupported</summary>
inline418.js:3 Encountered a panic!
__cargo_web_snippet_dc2fd915bd92f9e9c6a3bd15174f1414eee3dbaf @ inline418.js:3
__wbg_cargowebsnippetdc2fd915bd92f9e9c6a3bd15174f1414eee3dbaf_ce624dc8989b7508 @ stevenarella.js:262
__wbg_cargowebsnippetdc2fd915bd92f9e9c6a3bd15174f1414eee3dbaf_ce624dc8989b7508 @ bootstrap.js:122
stdweb::webcore::initialization::initialize::{{closure}}::hfaf8b55158d3d793 @ wasm-002ccbc2-399:21
std::panicking::rust_panic_with_hook::h5d8808384a53a826 @ wasm-002ccbc2-378:115
std::panicking::continue_panic_fmt::h821bed92a14cf5d5 @ wasm-002ccbc2-550:52
std::panicking::begin_panic_fmt::h83a0a8c60964976b @ wasm-002ccbc2-609:42
glutin::platform::platform::Context::new_windowed::h12dee54925d08191 @ wasm-002ccbc2-534:54
stevenarella::main2::hcc90ca13771299f1 @ wasm-002ccbc2-70:761
stevenarella::main::hbc764074c370a7d5 @ wasm-002ccbc2-949:2
main @ wasm-002ccbc2-950:2
main @ stevenarella.js:63
(anonymous) @ index.js:5
./index.js @ 0.bootstrap.js:178
__webpack_require__ @ bootstrap.js:165
Promise.then (async)
(anonymous) @ bootstrap.js:4
./bootstrap.js @ bootstrap.js:344
__webpack_require__ @ bootstrap.js:165
(anonymous) @ client:2
0 @ bootstrap.js:631
__webpack_require__ @ bootstrap.js:165
(anonymous) @ bootstrap.js:332
(anonymous) @ bootstrap.js:335
inline417.js:3 Panic error message: not yet implemented: Glutin-Blank: Platform unsupported
__cargo_web_snippet_97495987af1720d8a9a923fa4683a7b683e3acd6 @ inline417.js:3
__wbg_cargowebsnippet97495987af1720d8a9a923fa4683a7b683e3acd6_4d6a8b798885113c @ stevenarella.js:258
__wbg_cargowebsnippet97495987af1720d8a9a923fa4683a7b683e3acd6_4d6a8b798885113c @ bootstrap.js:125
stdweb::webcore::initialization::initialize::{{closure}}::hfaf8b55158d3d793 @ wasm-002ccbc2-399:72
std::panicking::rust_panic_with_hook::h5d8808384a53a826 @ wasm-002ccbc2-378:115
std::panicking::continue_panic_fmt::h821bed92a14cf5d5 @ wasm-002ccbc2-550:52
std::panicking::begin_panic_fmt::h83a0a8c60964976b @ wasm-002ccbc2-609:42
glutin::platform::platform::Context::new_windowed::h12dee54925d08191 @ wasm-002ccbc2-534:54
stevenarella::main2::hcc90ca13771299f1 @ wasm-002ccbc2-70:761
stevenarella::main::hbc764074c370a7d5 @ wasm-002ccbc2-949:2
main @ wasm-002ccbc2-950:2
main @ stevenarella.js:63
(anonymous) @ index.js:5
./index.js @ 0.bootstrap.js:178
__webpack_require__ @ bootstrap.js:165
Promise.then (async)
(anonymous) @ bootstrap.js:4
./bootstrap.js @ bootstrap.js:344
__webpack_require__ @ bootstrap.js:165
(anonymous) @ client:2
0 @ bootstrap.js:631
__webpack_require__ @ bootstrap.js:165
(anonymous) @ bootstrap.js:332
(anonymous) @ bootstrap.js:335
inline416.js:3 Panic location: /Users/admin/.cargo/git/checkouts/glutin-390166537a874d6b/1e48d32/glutin/src/platform/blank/mod.rs:32
__cargo_web_snippet_72fc447820458c720c68d0d8e078ede631edd723 @ inline416.js:3
__wbg_cargowebsnippet72fc447820458c720c68d0d8e078ede631edd723_60857d6a328c5ce1 @ stevenarella.js:254
__wbg_cargowebsnippet72fc447820458c720c68d0d8e078ede631edd723_60857d6a328c5ce1 @ bootstrap.js:128
stdweb::webcore::initialization::initialize::{{closure}}::hfaf8b55158d3d793 @ wasm-002ccbc2-399:104
std::panicking::rust_panic_with_hook::h5d8808384a53a826 @ wasm-002ccbc2-378:115
std::panicking::continue_panic_fmt::h821bed92a14cf5d5 @ wasm-002ccbc2-550:52
std::panicking::begin_panic_fmt::h83a0a8c60964976b @ wasm-002ccbc2-609:42
glutin::platform::platform::Context::new_windowed::h12dee54925d08191 @ wasm-002ccbc2-534:54
stevenarella::main2::hcc90ca13771299f1 @ wasm-002ccbc2-70:761
stevenarella::main::hbc764074c370a7d5 @ wasm-002ccbc2-949:2
main @ wasm-002ccbc2-950:2
main @ stevenarella.js:63
(anonymous) @ index.js:5
./index.js @ 0.bootstrap.js:178
__webpack_require__ @ bootstrap.js:165
Promise.then (async)
(anonymous) @ bootstrap.js:4
./bootstrap.js @ bootstrap.js:344
__webpack_require__ @ bootstrap.js:165
(anonymous) @ client:2
0 @ bootstrap.js:631
__webpack_require__ @ bootstrap.js:165
(anonymous) @ bootstrap.js:332
(anonymous) @ bootstrap.js:335
bootstrap.js:5 Error importing `index.js`: RuntimeError: unreachable
    at __rust_start_panic (wasm-function[1045]:1)
    at rust_panic (wasm-function[704]:31)
    at std::panicking::rust_panic_with_hook::h5d8808384a53a826 (wasm-function[378]:304)
    at std::panicking::continue_panic_fmt::h821bed92a14cf5d5 (wasm-function[550]:116)
    at std::panicking::begin_panic_fmt::h83a0a8c60964976b (wasm-function[609]:95)
    at glutin::platform::platform::Context::new_windowed::h12dee54925d08191 (wasm-function[534]:120)
    at stevenarella::main2::hcc90ca13771299f1 (wasm-function[70]:1695)
    at stevenarella::main::hbc764074c370a7d5 (wasm-function[949]:1)
    at main (wasm-function[950]:1)
    at Module.main (webpack:///../pkg/stevenarella.js?:63:66)
</details>

https://github.com/iceiix/stevenarella/issues/34 Investigate rendering backends, such as gfx-rs or wgpu

https://github.com/iceiix/stevenarella/tree/master/www

**Comment by iceiix** [comment]
A potential way forward: glow, see https://github.com/iceiix/stevenarella/issues/34#issuecomment-569573301

**Comment by iceiix** [comment]
With https://github.com/iceiix/stevenarella/pull/260#issuecomment-570968775 the new error is:

```
   Compiling glutin v0.22.0-alpha5
error[E0432]: unresolved import `self::platform_impl`
 --> .cargo/registry/src/github.com-1ecc6299db9ec823/glutin-0.22.0-alpha5/src/platform_impl/mod.rs:1:15
  |
1 | pub use self::platform_impl::*;
  |               ^^^^^^^^^^^^^ could not find `platform_impl` in `self`
error[E0433]: failed to resolve: could not find `Context` in `platform_impl`
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/glutin-0.22.0-alpha5/src/context.rs:182:24
    |
182 |         platform_impl::Context::new_headless(el, &pf_reqs, &gl_attr, size).map(
    |                        ^^^^^^^ could not find `Context` in `platform_impl`
error[E0433]: failed to resolve: could not find `Context` in `platform_impl`
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/glutin-0.22.0-alpha5/src/windowed.rs:362:24
    |
362 |         platform_impl::Context::new_windowed(wb, el, &pf_reqs, &gl_attr).map(
    |                        ^^^^^^^ could not find `Context` in `platform_impl`
error[E0412]: cannot find type `Context` in module `platform_impl`
  --> .cargo/registry/src/github.com-1ecc6299db9ec823/glutin-0.22.0-alpha5/src/context.rs:35:40
   |
35 |     pub(crate) context: platform_impl::Context,
   |                                        ^^^^^^^ not found in `platform_impl`
   |
help: possible candidates are found in other modules, you can import them into scope
   |
1  | use core::task::Context;
   |
1  | use crate::context::Context;
   |
1  | use std::task::Context;
   |

error[E0107]: wrong number of type arguments: expected 1, found 0
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/glutin-0.22.0-alpha5/src/context.rs:178:15
    |
178 |         size: dpi::PhysicalSize,
    |               ^^^^^^^^^^^^^^^^^ expected 1 type argument
error[E0107]: wrong number of type arguments: expected 1, found 0
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/glutin-0.22.0-alpha5/src/windowed.rs:180:32
    |
180 |     pub fn resize(&self, size: dpi::PhysicalSize) {
    |                                ^^^^^^^^^^^^^^^^^ expected 1 type argument
error: aborting due to 6 previous errors
```

**Comment by iceiix** [comment]
With (#277 and #278?), wasm-pack build now fails with a different error:

```
error[E0433]: failed to resolve: use of undeclared type or module `wasm_bindgen`
  --> registry/src/github.com-1ecc6299db9ec823/instant-0.1.2/src/wasm.rs:92:13
   |
92 |     let v = js! { return performance.now(); };
   |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ use of undeclared type or module `wasm_bindgen`
   |
   = note: this error originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)

error[E0433]: failed to resolve: use of undeclared type or module `WasmDescribe`
  --> registry/src/github.com-1ecc6299db9ec823/instant-0.1.2/src/wasm.rs:92:13
   |
92 |     let v = js! { return performance.now(); };
   |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ use of undeclared type or module `WasmDescribe`
   |
   = note: this error originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)

error[E0425]: cannot find function `inform` in this scope
  --> registry/src/github.com-1ecc6299db9ec823/instant-0.1.2/src/wasm.rs:92:13
   |
92 |     let v = js! { return performance.now(); };
   |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ not found in this scope
   |
   = note: this error originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)

error[E0425]: cannot find value `FUNCTION` in this scope
  --> registry/src/github.com-1ecc6299db9ec823/instant-0.1.2/src/wasm.rs:92:13
   |
92 |     let v = js! { return performance.now(); };
   |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ not found in this scope
   |
   = note: this error originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)

error: aborting due to 4 previous errors
```

**Comment by iceiix** [comment]
`cargo web start --target wasm32-unknown-unknown` however still fails with the platform_impl Context error, which would be solved by glow #262.

**Comment by TheGreatRambler** [comment]
I've been following this project and would love web support. What remains to make stevenarella build able for web? Anything I can do?

**Comment by iceiix** [comment]
@TheGreatRambler The biggest missing piece is currently WebGL compatibility. I think replacing steven_gl with a cross-platform wrapper would be a good way to solve this. Some more background and notes in https://github.com/iceiix/stevenarella/issues/34

I started migrating to glow (GL on Whatever) in https://github.com/iceiix/stevenarella/pull/262 but it is very incomplete. If you (or anyone) wants to work on it and can get it working, would be much appreciated. It is a large effort because of the extensive use of raw OpenGL through steven_gl, but switching off directly using OpenGL is (I believe) a necessary prerequisite for web support.

After rendering is working on the web, there will probably be a lot of other small compatibility changes needed to make it usable on the web, but rendering is the biggest blocker.

**Comment by iceiix** [comment]
Glow support (#262) is in, knocking down one of the largest blockers. #442 is still a blocker for rendering with WebGL, however. Lots has changed since I last tested this. Testing `cargo web start --target wasm32-unknown-unknown` on latest master:

```
   Compiling winit v0.24.0
error[E0433]: failed to resolve: use of undeclared crate or module `fs`
    --> protocol/src/protocol/mod.rs:1145:17
     |
1145 |             fs::File::create("last-packet")?.write_all(buf.get_ref())?;
     |                 ^^^^ not found in `fs`
     |
help: consider importing one of these items
     |
18   | use crate::types::metadata::io::sys::os::path::fs::File;
     |
18   | use crate::types::metadata::io::sys::process::File;
     |
18   | use std::fs::File;
     |
18   | use std_or_web::fs::File;
     |

   Compiling glutin v0.26.0
error[E0432]: unresolved import `self::platform_impl`
 --> registry/src/github.com-1ecc6299db9ec823/glutin-0.26.0/src/platform_impl/mod.rs:1:15
  |
1 | pub use self::platform_impl::*;
  |               ^^^^^^^^^^^^^ could not find `platform_impl` in `self`
error[E0412]: cannot find type `Context` in module `platform_impl`
  --> .cargo/registry/src/github.com-1ecc6299db9ec823/glutin-0.26.0/src/context.rs:35:40
   |
35 |     pub(crate) context: platform_impl::Context,
   |                                        ^^^^^^^ not found in `platform_impl`
   |
help: consider importing one of these items
   |
1  | use core::task::Context;
   |
1  | use crate::Context;
   |
1  | use std::task::Context;
   |

error[E0433]: failed to resolve: could not find `Context` in `platform_impl`
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/glutin-0.26.0/src/context.rs:154:24
    |
154 |         platform_impl::Context::new_headless(el, &pf_reqs, &gl_attr, size)
    |                        ^^^^^^^ not found in `platform_impl`
    |
help: consider importing one of these items
    |
1   | use core::task::Context;
    |
1   | use crate::Context;
    |
1   | use std::task::Context;
    |

error[E0433]: failed to resolve: could not find `Context` in `platform_impl`
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/glutin-0.26.0/src/windowed.rs:341:24
    |
341 |         platform_impl::Context::new_windowed(wb, el, &pf_reqs, &gl_attr).map(|(window, context)| {
    |                        ^^^^^^^ not found in `platform_impl`
    |
help: consider importing one of these items
    |
1   | use core::task::Context;
    |
1   | use crate::Context;
    |
1   | use std::task::Context;
    |
```

The recent glutin update (#334) is another possible source of incompatibilities.

Noticed that glow has removed stdweb support: https://github.com/grovesNL/glow/commit/7af2a26c7d9e26a712e8d9389f12f15f29c47475

`stdweb` is unfortunately unmaintained (2019): https://github.com/koute/stdweb/issues/403. The replacement is to use Web API bindings through [web-sys](https://lib.rs/crates/web-sys).
