### ISSUE TITLE
Potential security vulnerability found in the querystringify dependency?

### ISSUE THREAD

**Issue by iceiix** [iceiix/stevenarella#182]
https://github.com/iceiix/stevenarella/notifications shows "Potential security vulnerability found in the querystringify dependency":

<img width="750" alt="Screen Shot 2019-06-12 at 4 32 09 AM" src="https://user-images.githubusercontent.com/43691553/59348060-0dd7b180-8ccb-11e9-9d4b-0b0f83b3d5af.png">

when I click this notification, it goes back to https://github.com/iceiix/stevenarella and not any specific issue, so I'm opening this issue myself. But https://crates.io/crates/querystringify doesn't exist, this refers to an npm package:

```
www/package-lock.json
3819:    "querystringify": {
3821:      "resolved": "https://registry.npmjs.org/querystringify/-/querystringify-2.1.0.tgz",
4883:        "querystringify": "^2.0.0",
```

https://www.npmjs.com/package/querystringify last published 3 months ago

What was the vulnerability and why was it "potential"? Part of this new GitHub feature? https://help.github.com/en/articles/about-security-alerts-for-vulnerable-dependencies

Some discussion about this alert and how to resolve it at https://forums.meteor.com/t/solved-email-from-github-security-vulnerability-in-package-lock-json/43422/4

**Comment by stubclan** [comment]
@iceiix  Were you ever able to fix it? Having same issue!!
![image](https://user-images.githubusercontent.com/6322130/60385932-e6b40a80-9a54-11e9-9bcc-6354aedecc0a.png)

**Comment by iceiix** [comment]
@stubclan I dismissed the notification and it went away, but I was unable to view more details, so I'm not sure what this was. Maybe a glitch in GitHub?

https://www.google.com/search?q=%22Potential+security+vulnerability+found+in+the+querystringify+dependency%22 finds this very issue, sorry not sure how to fix it. The only other hit is https://github.com/KayeeNL/sitecore-jss-getting-started-vuejs/commit/34bbeecaab02ef9e6b877dfdb8f022c6afb751d9 which the author fixed by `npm update` presumably. I could try it on this repo, but doubt it is critical since `www/` actively used in this project yet.

**Comment by iceiix** [comment]
npm update claims it found 0 vulnerabilities:

```
www $ npm update

> fsevents@1.2.9 install steven/www/node_modules/fsevents
> node install

node-pre-gyp WARN Using needle for node-pre-gyp https download 
[fsevents] Success: "steven/www/node_modules/fsevents/lib/binding/Release/node-v57-darwin-x64/fse.node" is installed via remote
+ copy-webpack-plugin@5.0.3
+ webpack-cli@3.3.5
+ webpack-dev-server@3.7.2
+ webpack@4.35.2
added 31 packages from 64 contributors, removed 12 packages, updated 123 packages, moved 2 packages and audited 9089 packages in 25.663s
found 0 vulnerabilities
```

but the diff shows it did update querystring:

```
www $ git diff|grep querystring
         "querystring-es3": "^0.2.0",
     "querystring": {
     "querystringify": {
-      "resolved": "https://registry.npmjs.org/querystringify/-/querystringify-2.1.0.tgz",
+      "resolved": "https://registry.npmjs.org/querystringify/-/querystringify-2.1.1.tgz",
-        "querystringify": "^2.0.0",
+        "querystringify": "^2.1.1",
```
