### ISSUE TITLE
Unsupported command node parser minecraft:time

### ISSUE THREAD

**Issue by Bjornskjald** [iceiix/stevenarella#227]
Server: 1.14.4
Version: `d24b6cb`

```
thread '<unnamed>' panicked at 'unsupported command node parser minecraft:time', src/protocol/packet.rs:2862:22
stack backtrace:
   0: std::sys_common::backtrace::print
   1: std::panicking::default_hook::{{closure}}
   2: std::panicking::default_hook
   3: std::panicking::rust_panic_with_hook
   4: std::panicking::continue_panic_fmt
   5: std::panicking::begin_panic_fmt
   6: <stevenarella::protocol::packet::CommandNode as stevenarella::protocol::Serializable>::read_from
   7: <stevenarella::protocol::LenPrefixed<L,V> as stevenarella::protocol::Serializable>::read_from
   8: stevenarella::protocol::packet::packet_by_id
   9: stevenarella::protocol::Conn::read_packet
```

**Comment by rapenne-s** [comment]
I can confirm the same issue by connecting to a 1.14.4 with commit 45099165d990a5adc860eacc9050ce3dd3e20da0 and also d24b6cb599605b3b80f74fc409852191e8bee9ec (last commit when I write).

Tested on OpenBSD 6.6 amd64

**Comment by iceiix** [comment]
Need to add minecraft:time support to CommandNode serializable

https://minecraft.gamepedia.com/Argument_types#minecraft:time

https://github.com/iceiix/stevenarella/blob/d24b6cb599605b3b80f74fc409852191e8bee9ec/src/protocol/packet.rs#L2797

Also missing:

* minecraft:time
* brigadier:long - not actually used
* minecraft:nbt_compound_tag
* minecraft:nbt_tag
