### ISSUE TITLE
Crash when pressing Win+D

### ISSUE THREAD

**Issue by end360** [iceiix/stevenarella#275]
When pressing the windows key and d shortcut to minimize all apps the program panics with the message "The aspect ratio cannot be below zero, found: NaN".
[Console log](https://pastebin.com/HT9B83sY)

```
thread 'main' panicked at 'The aspect ratio cannot be below zero, found: NaN', C:\Users\user_\.cargo\registry\src\github.com-1ecc6299db9ec823\cgmath-0.17.0\src\projection.rs:117:9
stack backtrace:
   0: backtrace::backtrace::trace_unsynchronized
             at C:\Users\VssAdministrator\.cargo\registry\src\github.com-1ecc6299db9ec823\backtrace-0.3.37\src\backtrace\mod.rs:66
   1: std::sys_common::backtrace::_print_fmt
             at /rustc/4560ea788cb760f0a34127156c78e2552949f734\/src\libstd\sys_common\backtrace.rs:76
   2: std::sys_common::backtrace::_print::{{impl}}::fmt
             at /rustc/4560ea788cb760f0a34127156c78e2552949f734\/src\libstd\sys_common\backtrace.rs:60
   3: core::fmt::write
             at /rustc/4560ea788cb760f0a34127156c78e2552949f734\/src\libcore\fmt\mod.rs:1030
   4: std::io::Write::write_fmt<std::sys::windows::stdio::Stderr>
             at /rustc/4560ea788cb760f0a34127156c78e2552949f734\/src\libstd\io\mod.rs:1412
   5: std::sys_common::backtrace::_print
             at /rustc/4560ea788cb760f0a34127156c78e2552949f734\/src\libstd\sys_common\backtrace.rs:64
   6: std::sys_common::backtrace::print
             at /rustc/4560ea788cb760f0a34127156c78e2552949f734\/src\libstd\sys_common\backtrace.rs:49
   7: std::panicking::default_hook::{{closure}}
             at /rustc/4560ea788cb760f0a34127156c78e2552949f734\/src\libstd\panicking.rs:196
   8: std::panicking::default_hook
             at /rustc/4560ea788cb760f0a34127156c78e2552949f734\/src\libstd\panicking.rs:210
   9: std::panicking::rust_panic_with_hook
             at /rustc/4560ea788cb760f0a34127156c78e2552949f734\/src\libstd\panicking.rs:473
  10: std::panicking::continue_panic_fmt
             at /rustc/4560ea788cb760f0a34127156c78e2552949f734\/src\libstd\panicking.rs:380
  11: std::panicking::begin_panic_fmt
             at /rustc/4560ea788cb760f0a34127156c78e2552949f734\/src\libstd\panicking.rs:335
  12: cgmath::projection::<impl core::convert::From<cgmath::projection::PerspectiveFov<S>> for cgmath::matrix::Matrix4<S>>::from
  13: stevenarella::chunk_builder::build_func
  14: rand::Rng::sample
  15: std::panicking::try::do_call
  16: panic_unwind::__rust_maybe_catch_panic
             at /rustc/4560ea788cb760f0a34127156c78e2552949f734\/src\libpanic_unwind\lib.rs:80
  17: winit::platform_impl::platform::event_loop::runner::ELRShared<T>::send_event
  18: winit::platform_impl::platform::event_loop::runner::ELRShared<T>::send_event
  19: winit::platform_impl::platform::event_loop::normalize_pointer_pressure
  20: DefSubclassProc
  21: DefSubclassProc
  22: CallWindowProcW
  23: DispatchMessageW
  24: alloc::borrow::Cow<B>::into_owned
  25: alloc::borrow::Cow<B>::into_owned
  26: stevenarella::Game::tick
  27: <stevenarella::protocol::packet::handshake::serverbound::Handshake as stevenarella::protocol::PacketType>::write
  28: std::io::buffered::BufWriter<W>::flush_buf
  29: std::rt::lang_start_internal::{{closure}}
             at /rustc/4560ea788cb760f0a34127156c78e2552949f734\/src\libstd\rt.rs:49
  30: std::panicking::try::do_call<closure-0,i32>
             at /rustc/4560ea788cb760f0a34127156c78e2552949f734\/src\libstd\panicking.rs:292
  31: panic_unwind::__rust_maybe_catch_panic
             at /rustc/4560ea788cb760f0a34127156c78e2552949f734\/src\libpanic_unwind\lib.rs:80
  32: std::panicking::try
             at /rustc/4560ea788cb760f0a34127156c78e2552949f734\/src\libstd\panicking.rs:271
  33: std::panic::catch_unwind
             at /rustc/4560ea788cb760f0a34127156c78e2552949f734\/src\libstd\panic.rs:394
  34: std::rt::lang_start_internal
             at /rustc/4560ea788cb760f0a34127156c78e2552949f734\/src\libstd\rt.rs:48
  35: main
  36: invoke_main
             at d:\agent\_work\5\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:78
  37: __scrt_common_main_seh
             at d:\agent\_work\5\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
  38: BaseThreadInitThunk
  39: RtlUserThreadStart
```

**Comment by iceiix** [comment]
Win+D = show desktop, somehow this is causing the projection matrix in cgmath to become invalid. src/chunk_builder.rs build_func(). (Coincidentally was just looking at a cgmath alternative #271, may be a good time to investigate this area of the code further.)

**Comment by MeirBon** [comment]
@iceiix I have fixed this issue in a pull request. Are you okay with me merging pull requests once I have verified it works on my end and CI tests succeed?

**Comment by iceiix** [comment]
@MeirBon It would be good to have a review of pull requests if possible, I put some minor comments in https://github.com/iceiix/stevenarella/pull/332. I also invited a few other collaborators, who may (or may not) be able to help provide a second set of eyes on future changes.

However, as a small hobbyist side project, there isn't really any formal review structure or hierarchical organization, and there might not be anyone available to take a second look at any given time; of course, there is no expectation of commitment. I would say, it is a good idea to solicit feedback for other developers to look at the pull requests and offer feedback if possible, but if not, if no one is free, it is no big deal to merge if you've tested it and CI passed (more than I check for admittedly, not sure why [this failed on AppVeyor](https://github.com/iceiix/stevenarella/pull/332)), and you believe the change is a good idea.

I for one have been working on this project for years, but on and off, for stretches of months at a time. A bigger risk to this project in my estimation is not too much change, but too little change, stagnation from too few developers. 

So I'm thankful for your (and everyone else's) contributions, glad to have anyone aboard who can contribute improvements or fixes, within reason. This describes what I'm going for: an [OPEN Open Source Project](https://github.com/openopensource/openopensource.github.io):

> Individuals making significant and valuable contributions are given commit-access to the project to contribute as they see fit. This project is more like an open wiki than a standard guarded open source project.

at least for the time being. If a change breaks something, once identified it can be reverted or fixed, not too worried. If there are too many controversial or bad changes made by someone, can cross that bridge when we get there, but I trust that you will be reasonable in making changes to better the project. As well as the other contributors. Looking forward to seeing what you all can accomplish!
