### ISSUE TITLE
Input not working

### ISSUE THREAD

**Issue by wdcook4** [iceiix/stevenarella#282]
When running Steven, the main window's focused status very rarely if ever changes (however, the console does readily), despite Steven clearly animating and executing properly (camera spinning, console output) and I cannot give the window any input via mouse or keyboard and as such cannot log in and cannot connect to servers (attempts fail due to "unsupported" protocol versions (1.15.2 (578), 1.12 (335))

I am on Windows 10 1903 build 18362.592, running cargo 1.42.0-nightly (9d32b7b01 2020-01-26). If it makes any difference, I am using Razer peripherals and have not tested with standard peripherals.

This issue occurs on locally compiled versions as well as versions downloaded from the AppVeyor artifacts.

**Comment by NurMarvin** [comment]
Same issue here.
Using Windows 10, Version 1903 (OS Build 18362.592) as well.
Tried both the compiled binary from AppVeyor as well as a self compiled version using cargo 1.41.0 (626f0f40e 2019-12-03) without any success.

**Comment by TerriblePanda** [comment]
Same issue.

**Comment by SuperSandro2000** [comment]
Same issue on a beefy gaming rig.

**Comment by Kezii** [comment]
can confirm on linux

**Comment by jimliang** [comment]
Seems to be caused by glutin eventloop

**Comment by Kezii** [comment]
https://github.com/iceiix/stevenarella/blob/master/src/main.rs#L357

The code does the rendering in the event loop, and sleeps in it
It's probably bad design

**Comment by HoLLy-HaCKeR** [comment]
Not sure if related, but to me all input is extremely delayed, both on debug and release builds. The game renders fine, but trying to type in the login box will take at least half a minute to appear.

**Comment by iceiix** [comment]
> https://github.com/iceiix/stevenarella/blob/a06928e6da356fb4812f734bb34b147f87a8ce5c/src/main.rs#L357

This code was added in https://github.com/iceiix/stevenarella/commit/f349d516f22c72f9c6c1854e6ba36a9e66028e0d for configurable vsync, maybe should remove it. Need to test on Ubuntu and Windows…

**Comment by HoLLy-HaCKeR** [comment]
I commented out that line and it did not make a difference for me.

**Comment by Kezii** [comment]
It's probably better not to have input handling and rendering on the same thread / loop

Input events should be put in a queue asynchronously and the consumed all at once before every frame

**Comment by Hexdiract** [comment]
Same issue on FreeBSD 12.1, occasionally input responses normally for a brief moment, otherwise input takes like a minute for it to show up.

**Comment by enbyautumn** [comment]
has anyone got this fixed/has a workaround?

**Comment by Aeledfyr** [comment]
The root cause of this issue is that it only handles one event per frame, rather than dealing with all available events before rendering.  What it should be doing is handling `glutin`'s events in the event loop, and only drawing when `Event::RedrawRequested` is received.  Then, it can call the `request_redraw()` method on the window to schedule a redraw after all current events have been processed.

**Comment by eatmyvenom** [comment]
Just tossing in my confirmed on very strong computer

**Comment by roflmuffin** [comment]
I encountered this issue when launching on a 144hz monitor. I changed the framerate cap in the conf file to 144 and I was able to input without issues again.

**Comment by the-false-gamer** [comment]
I managed to try what @Aeledfyr mentioned. The game accepted input (almost) correctly, with some problems:
You cannot click on input boxes to "focus" on them.
You cannot move your character.
I'll try to make a full fix tommorow.

**Comment by iceiix** [comment]
@the-false-gamer want to PR your fix? :) (The event loop was changed from the sdl to glutin port so I'm sort of out of my element here, any help would be much appreciated!)

**Comment by the-false-gamer** [comment]
@iceiix sure. I forgot about my fix lol. I should fix input boxes before making a PR tho.

**Comment by MeirBon** [comment]
@the-false-gamer, @iceiix I fixed it. Check my pull request [here](https://github.com/iceiix/stevenarella/pull/315).
