### ISSUE TITLE
Position encoding is wrong for 1.15.2

### ISSUE THREAD

**Issue by Kezii** [iceiix/stevenarella#301]
I don't know if in older versions it was different, but for 1.15.2 Position encoding is wrong

This gives the correct result
```diff
diff --git a/protocol/src/protocol/mod.rs b/protocol/src/protocol/mod.rs
index 13be61a..9d4f42a 100644
--- a/protocol/src/protocol/mod.rs
+++ b/protocol/src/protocol/mod.rs
@@ -923,8 +923,8 @@ impl Serializable for Position {
         let pos = buf.read_u64::<BigEndian>()?;
         Ok(Position::new(
             ((pos as i64) >> 38) as i32,
-            (((pos as i64) >> 26) & 0xFFF) as i32,
-            ((pos as i64) << 38 >> 38) as i32
+            (((pos as i64)) & 0xFFF) as i32,
+            ((pos as i64) << 26 >> 38) as i32
         ))
     }
     fn write_to<W: io::Write>(&self, buf: &mut W) -> Result<(), Error> {

```

**Comment by iceiix** [comment]
https://wiki.vg/Protocol#Position 1.15.2
https://wiki.vg/index.php?title=Protocol&oldid=14902#Position 1.14.
https://wiki.vg/index.php?title=Protocol&oldid=14361#Position 1.13.2
https://wiki.vg/index.php?title=Protocol&oldid=13363#Position 1.12.2
https://wiki.vg/index.php?title=Protocol&oldid=7976#Position 1.10
https://wiki.vg/index.php?title=Protocol&oldid=7649#Position 1.9.2
https://wiki.vg/index.php?title=Protocol&oldid=6486#Position 1.8.3

```java
((x & 0x3FFFFFF) << 38) | ((z & 0x3FFFFFF) << 12) | (y & 0xFFF)
```

https://wiki.vg/Data_types#Position

https://wiki.vg/index.php?title=Data_types&oldid=15338#Position 1.15
```java
((x & 0x3FFFFFF) << 38) | ((z & 0x3FFFFFF) << 12) | (y & 0xFFF)
```

https://wiki.vg/index.php?title=Data_types&oldid=14271#Position 1.13
https://wiki.vg/index.php?title=Data_types&oldid=6055#Position 1.8
https://wiki.vg/index.php?title=Data_types&oldid=6055#Position 1.7

```java
 (x & 0x3FFFFFF) << 38 | (y & 0xFFF) << 26 | (z & 0x3FFFFFF)
```

Looks like this changed between 1.13 - 1.15

**Comment by Kezii** [comment]
I copy pasted from all the "Protocol" pages for all the versions:

```
1.7.5 ????
1.7.10  ((x & 0x3FFFFFF) << 38) | ((z & 0x3FFFFFF) << 12) | (y & 0xFFF)
1.8.9   ((x & 0x3FFFFFF) << 38) | ((z & 0x3FFFFFF) << 12) | (y & 0xFFF)
1.9.4   ((x & 0x3FFFFFF) << 38) | ((z & 0x3FFFFFF) << 12) | (y & 0xFFF)
1.10.2  ((x & 0x3FFFFFF) << 38) | ((z & 0x3FFFFFF) << 12) | (y & 0xFFF)
1.11.2  ((x & 0x3FFFFFF) << 38) | ((z & 0x3FFFFFF) << 12) | (y & 0xFFF)
1.12    ((x & 0x3FFFFFF) << 38) | ((z & 0x3FFFFFF) << 12) | (y & 0xFFF)
1.12.2  ((x & 0x3FFFFFF) << 38) | ((z & 0x3FFFFFF) << 12) | (y & 0xFFF)
1.13.2  ((x & 0x3FFFFFF) << 38) | ((z & 0x3FFFFFF) << 12) | (y & 0xFFF)
1.14.4  ((x & 0x3FFFFFF) << 38) | ((z & 0x3FFFFFF) << 12) | (y & 0xFFF)
1.15.2  ((x & 0x3FFFFFF) << 38) | ((z & 0x3FFFFFF) << 12) | (y & 0xFFF)

```

Seems like it was always coherent, except for the "Data_Types" pages that had the strange version until about 2019, in discrepancy with the other page

maybe it was just an error? I'm going to send a patch with the correct version
