### ISSUE TITLE
CI/CD consolidation/enhancements: macOS .app bundling

### ISSUE THREAD

**Issue by iceiix** [iceiix/stevenarella#352]
Follow-on to #351, which adds GitHub Actions, to complement the existing Azure Pipelines (#346), SourceHut (#176), and AppVeyor (#9) (also considered: CircleCI #174, Travis-CI #173). Consolidate all the CI systems into one, probably GitHub Actions, with a superset of the functionality:

- [x] `cargo clippy`, for reference this is executed in Azure Pipelines (move to GitHub Actions, probably fine as the same job as the build)
- [x] debug build without stripped symbols
- [x] Test on specific version of Rust (minimum supported stable 1.44.1)
- [ ] simplify filenames, Stevenarella.app, .exe, .
- [ ] macOS .app bundling

see notes in https://github.com/iceiix/stevenarella/pull/351#issuecomment-652233538

**Comment by MCOfficer** [comment]
Notes:
- for MacOS app bundling, here's an example: https://github.com/EndlessSkyCommunity/ESLauncher2/pull/42
- for clippy, there's [rust-clippy-check](https://github.com/marketplace/actions/rust-clippy-check). Even more interesting, the WIP [clippy action](https://github.com/actions-rs/clippy).
