### ISSUE TITLE
Remove server button not working (X connects to server instead of removing)

### ISSUE THREAD

**Issue by skillman623** [iceiix/stevenarella#355]
On the server list, the remove server button no longer functions.
I remember it functioning at one point.
Currently it connects to the server instead of removing it from the list.

OS Windows 10 home.
Graphics Nvidia.

**Comment by iceiix** [comment]
Confirmed, clicking "X" in the server list connects to the server on my system as well. "E" interestingly works as expected (edit). The buttons are highlighted correctly on mouseover, so this probably isn't a symptom of the mouse tracking issues (#334). Will have to regress to see when this broke.

**Comment by iceiix** [comment]
https://github.com/Thinkofname/steven/issues/49
