### ISSUE TITLE
1.15.1+: Entities not loading into the world

### ISSUE THREAD

**Issue by skillman623** [iceiix/stevenarella#357]
Both spawned and natural entities do not load into the world.
![Missing entities and blocks (fence pig laso)](https://user-images.githubusercontent.com/29513384/86516709-8b93c100-bde8-11ea-9a96-3d4c0b1473ee.PNG)
![Spawned entities do not appear, block load after world reload](https://user-images.githubusercontent.com/29513384/86516711-8df61b00-bde8-11ea-887b-504f2b69163e.PNG)
This may be related to #356

**Comment by iceiix** [comment]
Confirmed on 1.16.1, cannot see other entities (tested with another player). This worked at one point, I suspect it is a mishandling of the updated protocol.

**Comment by iceiix** [comment]
Testing on a 1.7.10 server, I can see other player entities (although they are still titled "MISSING", #141).

**Comment by iceiix** [comment]
Fixed handling the SpawnPlayer_f64_NoMeta packet in https://github.com/iceiix/stevenarella/commit/d362f136f1f8a5ff243664c54ec106cd23050291, player entities should now appear.

Other entities including mobs are not yet implemented, I'll split this remaining issue out separately into https://github.com/iceiix/stevenarella/issues/368 mobs
