### ISSUE TITLE
Logging to a file

### ISSUE THREAD

**Issue by skillman623** [iceiix/stevenarella#359]
There should be log files generated with console output to assist with debugging.

**Comment by Protonull** [comment]
Yeah, I've attempted to login to my server three times and each time it connects, starts loading chunks, but then crashes, taking the console window with it. And there's no log file so I don't even know where to begin in solving this issue.

**Comment by Protonull** [comment]
Huh, so I ran Stevenarella from a batch file because I'm also facing issues like #376, and it can prevent the console from auto closing after a crash. It's not a substitute for a log file, but can probably help :) here's the code

```
@echo off
title Stevenarella
cd %~dp0
cls
stevenarella.exe
pause
```

**Comment by iceiix** [comment]
We use the [log](https://lib.rs/crates/log) crate, a facade, so it should be straightforward to (also) log to a file. Currently it logs to stdout, and the console opened by typing "`" (this is currently the only use of the console, not yet used for chat: https://github.com/iceiix/stevenarella/issues/63)
