### ISSUE TITLE
Thread main panic- failed to fill whole buffer

### ISSUE THREAD

**Issue by skillman623** [iceiix/stevenarella#363]
When connecting to a 15w39c server client crashes with a panic.

> thread 'main' panicked at 'Err: IOError(Custom { kind: UnexpectedEof, error: "failed to fill whole buffer" })', src\server\mod.rs:570:33
stack backtrace:
   0: backtrace::backtrace::trace_unsynchronized
             at C:\Users\VssAdministrator\.cargo\registry\src\github.com-1ecc6299db9ec823\backtrace-0.3.46\src\backtrace\mod.rs:66
   1: std::sys_common::backtrace::_print_fmt
             at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7\/src\libstd\sys_common\backtrace.rs:78
   2: std::sys_common::backtrace::_print::{{impl}}::fmt
             at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7\/src\libstd\sys_common\backtrace.rs:59
   3: core::fmt::write
             at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7\/src\libcore\fmt\mod.rs:1069
   4: std::io::Write::write_fmt<std::sys::windows::stdio::Stderr>
             at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7\/src\libstd\io\mod.rs:1504
   5: std::sys_common::backtrace::_print
             at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7\/src\libstd\sys_common\backtrace.rs:62
   6: std::sys_common::backtrace::print
             at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7\/src\libstd\sys_common\backtrace.rs:49
   7: std::panicking::default_hook::{{closure}}
             at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7\/src\libstd\panicking.rs:198
   8: std::panicking::default_hook
             at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7\/src\libstd\panicking.rs:218
   9: std::panicking::rust_panic_with_hook
             at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7\/src\libstd\panicking.rs:511
  10: std::panicking::begin_panic_handler
             at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7\/src\libstd\panicking.rs:419
  11: std::panicking::begin_panic_fmt
             at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7\/src\libstd\panicking.rs:373
  12: stevenarella::server::Server::entity_tick
             at D:\Github\stevenarella\src\server\mod.rs:570
  13: stevenarella::server::Server::tick
             at D:\Github\stevenarella\src\server\mod.rs:463
  14: stevenarella::main2::{{closure}}
             at D:\Github\stevenarella\src\main.rs:374
  15: winit::platform_impl::platform::event_loop::{{impl}}::run_return::{{closure}}<(),closure-1>
             at C:\Users\PersonA\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.20.0\src\platform_impl\windows\event_loop.rs:211
  16: alloc::boxed::{{impl}}::call_mut<(winit::event::Event<()>, mut winit::event_loop::ControlFlow*),FnMut<(winit::event::Event<()>, mut winit::event_loop::ControlFlow*)>>
             at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7\src\liballoc\boxed.rs:1015
  17: winit::platform_impl::platform::event_loop::runner::{{impl}}::call_event_handler::{{closure}}<()>
             at C:\Users\PersonA\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.20.0\src\platform_impl\windows\event_loop\runner.rs:0
  18: std::panic::{{impl}}::call_once<(),closure-0>
             at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7\src\libstd\panic.rs:318
  19: std::panicking::try::do_call<std::panic::AssertUnwindSafe<closure-0>,()>
             at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7\src\libstd\panicking.rs:331
  20: _rust_try.llvm.17484202415343828450
  21: std::panicking::try<(),std::panic::AssertUnwindSafe<closure-0>>
             at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7\src\libstd\panicking.rs:274
  22: std::panic::catch_unwind<std::panic::AssertUnwindSafe<closure-0>,()>
             at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7\src\libstd\panic.rs:394
  23: winit::platform_impl::platform::event_loop::runner::EventLoopRunner<()>::call_event_handler<()>
             at C:\Users\PersonA\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.20.0\src\platform_impl\windows\event_loop\runner.rs:410
  24: winit::platform_impl::platform::event_loop::runner::EventLoopRunner<()>::events_cleared<()>
             at C:\Users\PersonA\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.20.0\src\platform_impl\windows\event_loop\runner.rs:352
  25: winit::platform_impl::platform::event_loop::runner::ELRShared<()>::events_cleared<()>
             at C:\Users\PersonA\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.20.0\src\platform_impl\windows\event_loop\runner.rs:117
  26: winit::platform_impl::platform::event_loop::EventLoop<()>::run_return<(),closure-1>
             at C:\Users\PersonA\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.20.0\src\platform_impl\windows\event_loop.rs:234
  27: winit::platform_impl::platform::event_loop::EventLoop<()>::run<(),closure-1>
             at C:\Users\PersonA\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.20.0\src\platform_impl\windows\event_loop.rs:196
  28: winit::event_loop::EventLoop<()>::run<(),closure-1>
             at C:\Users\PersonA\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.20.0\src\event_loop.rs:148
  29: stevenarella::main2
             at D:\Github\stevenarella\src\main.rs:336
  30: stevenarella::main
             at D:\Github\stevenarella\src\main.rs:219
  31: std::rt::lang_start::{{closure}}<()>
             at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7\src\libstd\rt.rs:67
  32: std::rt::lang_start_internal::{{closure}}
             at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7\/src\libstd\rt.rs:52
  33: std::panicking::try::do_call
             at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7\/src\libstd\panicking.rs:331
  34: std::panicking::try
             at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7\/src\libstd\panicking.rs:274
  35: std::panic::catch_unwind
             at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7\/src\libstd\panic.rs:394
  36: std::rt::lang_start_internal
             at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7\/src\libstd\rt.rs:51
  37: std::rt::lang_start<()>
             at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7\src\libstd\rt.rs:67
  38: invoke_main
             at d:\A01\_work\6\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:78
  39: __scrt_common_main_seh
             at d:\A01\_work\6\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
  40: BaseThreadInitThunk
  41: RtlUserThreadStart

**Comment by skillman623** [comment]
Got this same error; the official client got kicked at the same time as Stevenarella crashed. I didn't catch the message on the client (console wasn't up and had clicked back to server list).

**Comment by iceiix** [comment]
Protocol parsing error, can you reproduce with `--network-debug` and attach the contents of last-packet? (this will show the packet failing to parse)

**Comment by iceiix** [comment]
@skillman623 If you are able to repro with --network-debug can you attach the logs and last-packet and reopen this issue?
