### ISSUE TITLE
1.16.4: Particle_f64: us.hypixel.net : Main thread panic-Failed to read all of packet 0x23, had 16 bytes left

### ISSUE THREAD

**Issue by skillman623** [iceiix/stevenarella#377]
Secondary issue from #376. 
Tested with latest commit 7869893038a4b5699f180ba6afa84bd1e29cc1f0
Connection to crash while connecting to us.hypixel.net after connecting for a while.
Panic is as follows

> thread 'main' panicked at 'Err: Err("Failed to read all of packet 0x23, had 16 bytes left")', src\server\mod.rs:571:33
stack backtrace:
   0: backtrace::backtrace::trace_unsynchronized
             at C:\Users\VssAdministrator\.cargo\registry\src\github.com-1ecc6299db9ec823\backtrace-0.3.46\src\backtrace\mod.rs:66
   1: std::sys_common::backtrace::_print_fmt
             at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4\/src\libstd\sys_common\backtrace.rs:78
   2: std::sys_common::backtrace::_print::{{impl}}::fmt
             at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4\/src\libstd\sys_common\backtrace.rs:59
   3: core::fmt::write
             at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4\/src\libcore\fmt\mod.rs:1069
   4: std::io::Write::write_fmt<std::sys::windows::stdio::Stderr>
             at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4\/src\libstd\io\mod.rs:1504
   5: std::sys_common::backtrace::_print
             at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4\/src\libstd\sys_common\backtrace.rs:62
   6: std::sys_common::backtrace::print
             at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4\/src\libstd\sys_common\backtrace.rs:49
   7: std::panicking::default_hook::{{closure}}
             at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4\/src\libstd\panicking.rs:198
   8: std::panicking::default_hook
             at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4\/src\libstd\panicking.rs:218
   9: std::panicking::rust_panic_with_hook
             at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4\/src\libstd\panicking.rs:511
  10: std::panicking::begin_panic_handler
             at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4\/src\libstd\panicking.rs:419
  11: std::panicking::begin_panic_fmt
             at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4\/src\libstd\panicking.rs:373
  12: stevenarella::server::Server::entity_tick
             at C:\Users\User\Documents\GitHub\stevenarella\src\server\mod.rs:571
  13: stevenarella::server::Server::tick
             at C:\Users\User\Documents\GitHub\stevenarella\src\server\mod.rs:463
  14: stevenarella::main2::{{closure}}
             at C:\Users\User\Documents\GitHub\stevenarella\src\main.rs:374
  15: winit::platform_impl::platform::event_loop::{{impl}}::run_return::{{closure}}<(),closure-1>
             at C:\Users\User\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.20.0\src\platform_impl\windows\event_loop.rs:211
  16: alloc::boxed::{{impl}}::call_mut
             at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4\src\liballoc\boxed.rs:1015
  17: winit::platform_impl::platform::event_loop::runner::{{impl}}::call_event_handler::{{closure}}
             at C:\Users\User\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.20.0\src\platform_impl\windows\event_loop\runner.rs:412
  18: std::panic::{{impl}}::call_once
             at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4\src\libstd\panic.rs:318
  19: std::panicking::try::do_call
             at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4\src\libstd\panicking.rs:331
  20: std::panicking::try
             at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4\src\libstd\panicking.rs:274
  21: std::panic::catch_unwind
             at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4\src\libstd\panic.rs:394
  22: winit::platform_impl::platform::event_loop::runner::EventLoopRunner<()>::call_event_handler
             at C:\Users\User\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.20.0\src\platform_impl\windows\event_loop\runner.rs:410
  23: winit::platform_impl::platform::event_loop::runner::EventLoopRunner<()>::events_cleared<()>
             at C:\Users\User\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.20.0\src\platform_impl\windows\event_loop\runner.rs:352
  24: winit::platform_impl::platform::event_loop::runner::ELRShared<()>::events_cleared
             at C:\Users\User\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.20.0\src\platform_impl\windows\event_loop\runner.rs:117
  25: winit::platform_impl::platform::event_loop::EventLoop<()>::run_return
             at C:\Users\User\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.20.0\src\platform_impl\windows\event_loop.rs:234
  26: winit::platform_impl::platform::event_loop::EventLoop<()>::run<(),closure-1>
             at C:\Users\User\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.20.0\src\platform_impl\windows\event_loop.rs:196
  27: winit::event_loop::EventLoop<()>::run<(),closure-1>
             at C:\Users\User\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.20.0\src\event_loop.rs:148
  28: stevenarella::main2
             at C:\Users\User\Documents\GitHub\stevenarella\src\main.rs:336
  29: stevenarella::main
             at C:\Users\User\Documents\GitHub\stevenarella\src\main.rs:219
  30: std::rt::lang_start::{{closure}}<()>
             at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4\src\libstd\rt.rs:67
  31: std::rt::lang_start_internal::{{closure}}
             at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4\/src\libstd\rt.rs:52
  32: std::panicking::try::do_call
             at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4\/src\libstd\panicking.rs:331
  33: std::panicking::try
             at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4\/src\libstd\panicking.rs:274
  34: std::panic::catch_unwind
             at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4\/src\libstd\panic.rs:394
  35: std::rt::lang_start_internal
             at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4\/src\libstd\rt.rs:51
  36: main
  37: invoke_main
             at d:\A01\_work\6\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:78
  38: __scrt_common_main_seh
             at d:\A01\_work\6\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
  39: BaseThreadInitThunk
  40: RtlUserThreadStart
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

Full log with network debug is attached.
[Failed to read all of packet 0x23.txt](https://github.com/iceiix/stevenarella/files/4963501/Failed.to.read.all.of.packet.0x23.txt)

**Comment by iceiix** [comment]
If 1.16.1 (couldn't find the protocol version number from the logs, but from the packet IDs listed it looks like either 1.16.x or 1.14.x), packet 0x23 is for particle/sound effects: https://wiki.vg/Protocol#Effect 
History of this packet, need to double-check it is parsed correctly in each version:

```
v1_7_10.rs:            0x2a => Particle_Named
v1_8_9.rs:            0x2a => Particle_VarIntArray
v1_9.rs:            0x22 => Particle_VarIntArray
v1_9_2.rs:            0x22 => Particle_VarIntArray
v15w39c.rs:            0x22 => Particle_VarIntArray
v18w50a.rs:            0x24 => Particle_VarIntArray
v19w02a.rs:            0x24 => Particle_Data
v1_10_2.rs:            0x22 => Particle_VarIntArray
v1_11_2.rs:            0x22 => Particle_VarIntArray
v1_12_2.rs:            0x22 => Particle_VarIntArray
v1_13_2.rs:            0x24 => Particle_Data
v1_14.rs:            0x23 => Particle_Data
v1_14_1.rs:            0x23 => Particle_Data
v1_14_2.rs:            0x23 => Particle_Data
v1_14_3.rs:            0x23 => Particle_Data
v1_14_4.rs:            0x23 => Particle_Data
v1_15.rs:            0x24 => Particle_f64
v1_16_1.rs:            0x23 => Particle_f64
```

**Comment by iceiix** [comment]
The packet definition has IDs that need to be updated:

```
protocol/src/protocol/versions/v1_16_1.rs:            0x23 => Particle_f64
protocol/src/protocol/versions/v1_16_4.rs:            0x22 => Particle_f64
protocol/src/protocol/versions/v1_15.rs:            0x24 => Particle_f64
```

1.16.4, dust is 14 https://wiki.vg/Protocol#Particle
1.16.1, https://wiki.vg/index.php?title=Pre-release_protocol&oldid=15895#Particle
1.15.2, dust is 14 https://wiki.vg/index.php?title=Protocol&oldid=16067#Particle
1.15.1 https://wiki.vg/index.php?title=Pre-release_protocol&oldid=15241#Particle

I have Particle_f64 defined as:

```
                field block_state: VarInt = when(|p: &Particle_f64| p.particle_id == 3 || p.particle_id == 20),
                field red: f32 = when(|p: &Particle_f64| p.particle_id == 11),
                field green: f32 = when(|p: &Particle_f64| p.particle_id == 11),
                field blue: f32 = when(|p: &Particle_f64| p.particle_id == 11),
                field scale: f32 = when(|p: &Particle_f64| p.particle_id == 11),
                field item: Option<nbt::NamedTag> = when(|p: &Particle_f64| p.particle_id == 27),
            }
```

block and falling_dust have a block_state, which was 3 and 20 above, but is now 3 and 23
dust (red, green, blue, scale) was 11, is now 14
item was 27, is now 32

It is hard to tell from the wiki.vg documentation when these IDs changed, but found that PrismarineJS had the same problem: https://github.com/PrismarineJS/minecraft-data/issues/316 https://github.com/PrismarineJS/minecraft-data/commit/9dfc8e35f76a5d49e55a736498f43256b9340f9e shows 14/23//32 are used in: 1.14.1, 1.14.3, 1.14.4, 1.14, 1.15.1, 1.15.2, 1.15, 1.16-rc1, 1.16.1, 1.16, 20w13b... this affects a lot of versions: 

* v1_14, v1_14_1, v1_14_2, v1_14_3, v1_14_4 Particle_Data
* v1_15 Particle_f64
* v1_16_1, v1_16_4 Particle_f64

v1_13_2 Particle_Data has the old IDs: https://github.com/PrismarineJS/minecraft-data/blob/master/data/pc/1.13.2/protocol.json#L89. 

(No change) Particle_VarIntArray is used by v15w39c, v18w50a, v1_10_2, v1_11_2, v1_12_2, v1_8_9, v1_9, v1_9_2 and Particle_Named by 1.7.10

Update Particle_f64 and Particle_Data to the new IDs, and split Particle_Data for v1_13_2 (and v19w02a?) with the old IDs

**Comment by iceiix** [comment]
Revisiting the particle IDs per https://github.com/iceiix/stevenarella/pull/640#issuecomment-1003591671:

1.18.1 https://wiki.vg/Protocol#Particle - 2,3 BlockState, up to 87
1.17.1 https://wiki.vg/index.php?title=Protocol&oldid=16918#Particle - same
1.17 https://wiki.vg/index.php?title=Protocol&oldid=16866#Particle
1.16.5 https://wiki.vg/index.php?title=Protocol&oldid=16681#Particle
1.16.4 https://wiki.vg/index.php?title=Protocol&oldid=16317#Particle
1.16.3 https://wiki.vg/index.php?title=Protocol&oldid=16091#Particle
1.15.2 https://wiki.vg/index.php?title=Protocol&oldid=16067#Particle
1.14.4 https://wiki.vg/index.php?title=Protocol&oldid=15346#Particle
1.13.2 https://wiki.vg/index.php?title=Protocol&oldid=14889#Particle
1.13.1 https://wiki.vg/index.php?title=Protocol&oldid=14301#Particle
1.12.2 https://wiki.vg/index.php?title=Protocol&oldid=14204#Particle
1.12.1 https://wiki.vg/index.php?title=Protocol&oldid=13339#Particle
1.12 https://wiki.vg/index.php?title=Protocol&oldid=13223#Particle
1.11.2 https://wiki.vg/index.php?title=Protocol&oldid=8543#Particle
1.11 https://wiki.vg/index.php?title=Protocol&oldid=8405#Particle
1.10.2 https://wiki.vg/index.php?title=Protocol&oldid=8235#Particle
1.9.4 https://wiki.vg/index.php?title=Protocol&oldid=7959#Particle
1.9.2 https://wiki.vg/index.php?title=Protocol&oldid=7817#Particle
1.9 https://wiki.vg/index.php?title=Protocol&oldid=7617#Particle
1.8.9 https://wiki.vg/index.php?title=Protocol&oldid=7368#Particle
1.7.10 https://wiki.vg/index.php?title=Protocol&oldid=6003#Particle

Current protocol packet definitions:

```rust
protocol/src/protocol/versions/v1_18_1.rs:            0x24 => Particle_f64
protocol/src/protocol/versions/v1_17_1.rs:            0x24 => Particle_f64
protocol/src/protocol/versions/v1_16_4.rs:            0x22 => Particle_f64
protocol/src/protocol/versions/v1_16_1.rs:            0x23 => Particle_f64
protocol/src/protocol/versions/v1_15.rs:            0x24 => Particle_f64
protocol/src/protocol/versions/v1_14_4.rs:            0x23 => Particle_f32
protocol/src/protocol/versions/v1_14_3.rs:            0x23 => Particle_f32
protocol/src/protocol/versions/v1_14_2.rs:            0x23 => Particle_f32
protocol/src/protocol/versions/v1_14_1.rs:            0x23 => Particle_f32
protocol/src/protocol/versions/v1_14.rs:            0x23 => Particle_f32
protocol/src/protocol/versions/v1_13_2.rs:            0x24 => Particle_f32
protocol/src/protocol/versions/v1_12_2.rs:            0x22 => Particle_VarIntArray
protocol/src/protocol/versions/v1_11_2.rs:            0x22 => Particle_VarIntArray
protocol/src/protocol/versions/v1_10_2.rs:            0x22 => Particle_VarIntArray
protocol/src/protocol/versions/v1_9_2.rs:            0x22 => Particle_VarIntArray
protocol/src/protocol/versions/v1_9.rs:            0x22 => Particle_VarIntArray
protocol/src/protocol/versions/v1_8_9.rs:            0x2a => Particle_VarIntArray
protocol/src/protocol/versions/v1_7_10.rs:            0x2a => Particle_Named
```

and:

```rust
           /// Particle spawns particles at the target location with the various
            /// modifiers.
            packet Particle_f64 {
                field particle_id: i32 =,
                field long_distance: bool =,
                field x: f64 =,
                field y: f64 =,
                field z: f64 =,
                field offset_x: f32 =,
                field offset_y: f32 =,
                field offset_z: f32 =,
                field speed: f32 =,
                field count: i32 =,
                field block_state: VarInt = when(|p: &Particle_f64| p.particle_id == 4 || p.particle_id == 25),
                field red: f32 = when(|p: &Particle_f64| p.particle_id == 15 || p.particle_id == 16),
                field green: f32 = when(|p: &Particle_f64| p.particle_id == 15 || p.particle_id == 16),
                field blue: f32 = when(|p: &Particle_f64| p.particle_id == 15 || p.particle_id == 16),
                field scale: f32 = when(|p: &Particle_f64| p.particle_id == 15 || p.particle_id == 16),
                field to_red: f32 = when(|p: &Particle_f64| p.particle_id == 16),
                field to_green: f32 = when(|p: &Particle_f64| p.particle_id == 16),
                field to_blue: f32 = when(|p: &Particle_f64| p.particle_id == 16),
                field item: Option<nbt::NamedTag> = when(|p: &Particle_f64| p.particle_id == 36),
                field origin_x: f64 = when(|p: &Particle_f64| p.particle_id == 37),
                field origin_y: f64 = when(|p: &Particle_f64| p.particle_id == 37),
                field origin_z: f64 = when(|p: &Particle_f64| p.particle_id == 37),
                field dest_x: f64 = when(|p: &Particle_f64| p.particle_id == 37),
                field dest_y: f64 = when(|p: &Particle_f64| p.particle_id == 37),
                field dest_z: f64 = when(|p: &Particle_f64| p.particle_id == 37),
                field ticks: f64 = when(|p: &Particle_f64| p.particle_id == 37),
            }
            packet Particle_f32 {
                field particle_id: i32 =,
                field long_distance: bool =,
                field x: f32 =,
                field y: f32 =,
                field z: f32 =,
                field offset_x: f32 =,
                field offset_y: f32 =,
                field offset_z: f32 =,
                field speed: f32 =,
                field count: i32 =,
                field block_state: VarInt = when(|p: &Particle_f32| p.particle_id == 4 || p.particle_id == 25),
                field red: f32 = when(|p: &Particle_f32| p.particle_id == 15 || p.particle_id == 16),
                field green: f32 = when(|p: &Particle_f32| p.particle_id == 15 || p.particle_id == 16),
                field blue: f32 = when(|p: &Particle_f32| p.particle_id == 15 || p.particle_id == 16),
                field scale: f32 = when(|p: &Particle_f32| p.particle_id == 15 || p.particle_id == 16),
                field to_red: f32 = when(|p: &Particle_f32| p.particle_id == 16),
                field to_green: f32 = when(|p: &Particle_f32| p.particle_id == 16),
                field to_blue: f32 = when(|p: &Particle_f32| p.particle_id == 16),
                field item: Option<nbt::NamedTag> = when(|p: &Particle_f32| p.particle_id == 36),
                field origin_x: f64 = when(|p: &Particle_f32| p.particle_id == 37),
                field origin_y: f64 = when(|p: &Particle_f32| p.particle_id == 37),
                field origin_z: f64 = when(|p: &Particle_f32| p.particle_id == 37),
                field dest_x: f64 = when(|p: &Particle_f32| p.particle_id == 37),
                field dest_y: f64 = when(|p: &Particle_f32| p.particle_id == 37),
                field dest_z: f64 = when(|p: &Particle_f32| p.particle_id == 37),
                field ticks: f64 = when(|p: &Particle_f32| p.particle_id == 37),
            }
            packet Particle_VarIntArray {
                field particle_id: i32 =,
                field long_distance: bool =,
                field x: f32 =,
                field y: f32 =,
                field z: f32 =,
                field offset_x: f32 =,
                field offset_y: f32 =,
                field offset_z: f32 =,
                field speed: f32 =,
                field count: i32 =,
                field data1: VarInt = when(|p: &Particle_VarIntArray| p.particle_id == 36 || p.particle_id == 37 || p.particle_id == 38 || p.particle_id == 46),
                field data2: VarInt = when(|p: &Particle_VarIntArray| p.particle_id == 36),
            }
            packet Particle_Named {
                field particle_id: String =,
                field x: f32 =,
                field y: f32 =,
                field z: f32 =,
                field offset_x: f32 =,
                field offset_y: f32 =,
                field offset_z: f32 =,
                field speed: f32 =,
                field count: i32 =,
            }
```

where did these particle IDs come from? were they not the same for all of 1.7.10 - 1.18.1?

**Comment by terrarier2111** [comment]
> Revisiting the particle IDs per [#640 (comment)](https://github.com/iceiix/stevenarella/pull/640#issuecomment-1003591671):
> 
> 1.18.1 https://wiki.vg/Protocol#Particle - 2,3 BlockState, up to 87 1.17.1 https://wiki.vg/index.php?title=Protocol&oldid=16918#Particle - same 1.17 https://wiki.vg/index.php?title=Protocol&oldid=16866#Particle 1.16.5 https://wiki.vg/index.php?title=Protocol&oldid=16681#Particle 1.16.4 https://wiki.vg/index.php?title=Protocol&oldid=16317#Particle 1.16.3 https://wiki.vg/index.php?title=Protocol&oldid=16091#Particle 1.15.2 https://wiki.vg/index.php?title=Protocol&oldid=16067#Particle 1.14.4 https://wiki.vg/index.php?title=Protocol&oldid=15346#Particle 1.13.2 https://wiki.vg/index.php?title=Protocol&oldid=14889#Particle 1.13.1 https://wiki.vg/index.php?title=Protocol&oldid=14301#Particle 1.12.2 https://wiki.vg/index.php?title=Protocol&oldid=14204#Particle 1.12.1 https://wiki.vg/index.php?title=Protocol&oldid=13339#Particle 1.12 https://wiki.vg/index.php?title=Protocol&oldid=13223#Particle 1.11.2 https://wiki.vg/index.php?title=Protocol&oldid=8543#Particle 1.11 https://wiki.vg/index.php?title=Protocol&oldid=8405#Particle 1.10.2 https://wiki.vg/index.php?title=Protocol&oldid=8235#Particle 1.9.4 https://wiki.vg/index.php?title=Protocol&oldid=7959#Particle 1.9.2 https://wiki.vg/index.php?title=Protocol&oldid=7817#Particle 1.9 https://wiki.vg/index.php?title=Protocol&oldid=7617#Particle 1.8.9 https://wiki.vg/index.php?title=Protocol&oldid=7368#Particle 1.7.10 https://wiki.vg/index.php?title=Protocol&oldid=6003#Particle
> 
> Current protocol packet definitions:
> 
> ```rust
> protocol/src/protocol/versions/v1_18_1.rs:            0x24 => Particle_f64
> protocol/src/protocol/versions/v1_17_1.rs:            0x24 => Particle_f64
> protocol/src/protocol/versions/v1_16_4.rs:            0x22 => Particle_f64
> protocol/src/protocol/versions/v1_16_1.rs:            0x23 => Particle_f64
> protocol/src/protocol/versions/v1_15.rs:            0x24 => Particle_f64
> protocol/src/protocol/versions/v1_14_4.rs:            0x23 => Particle_f32
> protocol/src/protocol/versions/v1_14_3.rs:            0x23 => Particle_f32
> protocol/src/protocol/versions/v1_14_2.rs:            0x23 => Particle_f32
> protocol/src/protocol/versions/v1_14_1.rs:            0x23 => Particle_f32
> protocol/src/protocol/versions/v1_14.rs:            0x23 => Particle_f32
> protocol/src/protocol/versions/v1_13_2.rs:            0x24 => Particle_f32
> protocol/src/protocol/versions/v1_12_2.rs:            0x22 => Particle_VarIntArray
> protocol/src/protocol/versions/v1_11_2.rs:            0x22 => Particle_VarIntArray
> protocol/src/protocol/versions/v1_10_2.rs:            0x22 => Particle_VarIntArray
> protocol/src/protocol/versions/v1_9_2.rs:            0x22 => Particle_VarIntArray
> protocol/src/protocol/versions/v1_9.rs:            0x22 => Particle_VarIntArray
> protocol/src/protocol/versions/v1_8_9.rs:            0x2a => Particle_VarIntArray
> protocol/src/protocol/versions/v1_7_10.rs:            0x2a => Particle_Named
> ```
> 
> and:
> 
> ```rust
>            /// Particle spawns particles at the target location with the various
>             /// modifiers.
>             packet Particle_f64 {
>                 field particle_id: i32 =,
>                 field long_distance: bool =,
>                 field x: f64 =,
>                 field y: f64 =,
>                 field z: f64 =,
>                 field offset_x: f32 =,
>                 field offset_y: f32 =,
>                 field offset_z: f32 =,
>                 field speed: f32 =,
>                 field count: i32 =,
>                 field block_state: VarInt = when(|p: &Particle_f64| p.particle_id == 4 || p.particle_id == 25),
>                 field red: f32 = when(|p: &Particle_f64| p.particle_id == 15 || p.particle_id == 16),
>                 field green: f32 = when(|p: &Particle_f64| p.particle_id == 15 || p.particle_id == 16),
>                 field blue: f32 = when(|p: &Particle_f64| p.particle_id == 15 || p.particle_id == 16),
>                 field scale: f32 = when(|p: &Particle_f64| p.particle_id == 15 || p.particle_id == 16),
>                 field to_red: f32 = when(|p: &Particle_f64| p.particle_id == 16),
>                 field to_green: f32 = when(|p: &Particle_f64| p.particle_id == 16),
>                 field to_blue: f32 = when(|p: &Particle_f64| p.particle_id == 16),
>                 field item: Option<nbt::NamedTag> = when(|p: &Particle_f64| p.particle_id == 36),
>                 field origin_x: f64 = when(|p: &Particle_f64| p.particle_id == 37),
>                 field origin_y: f64 = when(|p: &Particle_f64| p.particle_id == 37),
>                 field origin_z: f64 = when(|p: &Particle_f64| p.particle_id == 37),
>                 field dest_x: f64 = when(|p: &Particle_f64| p.particle_id == 37),
>                 field dest_y: f64 = when(|p: &Particle_f64| p.particle_id == 37),
>                 field dest_z: f64 = when(|p: &Particle_f64| p.particle_id == 37),
>                 field ticks: f64 = when(|p: &Particle_f64| p.particle_id == 37),
>             }
>             packet Particle_f32 {
>                 field particle_id: i32 =,
>                 field long_distance: bool =,
>                 field x: f32 =,
>                 field y: f32 =,
>                 field z: f32 =,
>                 field offset_x: f32 =,
>                 field offset_y: f32 =,
>                 field offset_z: f32 =,
>                 field speed: f32 =,
>                 field count: i32 =,
>                 field block_state: VarInt = when(|p: &Particle_f32| p.particle_id == 4 || p.particle_id == 25),
>                 field red: f32 = when(|p: &Particle_f32| p.particle_id == 15 || p.particle_id == 16),
>                 field green: f32 = when(|p: &Particle_f32| p.particle_id == 15 || p.particle_id == 16),
>                 field blue: f32 = when(|p: &Particle_f32| p.particle_id == 15 || p.particle_id == 16),
>                 field scale: f32 = when(|p: &Particle_f32| p.particle_id == 15 || p.particle_id == 16),
>                 field to_red: f32 = when(|p: &Particle_f32| p.particle_id == 16),
>                 field to_green: f32 = when(|p: &Particle_f32| p.particle_id == 16),
>                 field to_blue: f32 = when(|p: &Particle_f32| p.particle_id == 16),
>                 field item: Option<nbt::NamedTag> = when(|p: &Particle_f32| p.particle_id == 36),
>                 field origin_x: f64 = when(|p: &Particle_f32| p.particle_id == 37),
>                 field origin_y: f64 = when(|p: &Particle_f32| p.particle_id == 37),
>                 field origin_z: f64 = when(|p: &Particle_f32| p.particle_id == 37),
>                 field dest_x: f64 = when(|p: &Particle_f32| p.particle_id == 37),
>                 field dest_y: f64 = when(|p: &Particle_f32| p.particle_id == 37),
>                 field dest_z: f64 = when(|p: &Particle_f32| p.particle_id == 37),
>                 field ticks: f64 = when(|p: &Particle_f32| p.particle_id == 37),
>             }
>             packet Particle_VarIntArray {
>                 field particle_id: i32 =,
>                 field long_distance: bool =,
>                 field x: f32 =,
>                 field y: f32 =,
>                 field z: f32 =,
>                 field offset_x: f32 =,
>                 field offset_y: f32 =,
>                 field offset_z: f32 =,
>                 field speed: f32 =,
>                 field count: i32 =,
>                 field data1: VarInt = when(|p: &Particle_VarIntArray| p.particle_id == 36 || p.particle_id == 37 || p.particle_id == 38 || p.particle_id == 46),
>                 field data2: VarInt = when(|p: &Particle_VarIntArray| p.particle_id == 36),
>             }
>             packet Particle_Named {
>                 field particle_id: String =,
>                 field x: f32 =,
>                 field y: f32 =,
>                 field z: f32 =,
>                 field offset_x: f32 =,
>                 field offset_y: f32 =,
>                 field offset_z: f32 =,
>                 field speed: f32 =,
>                 field count: i32 =,
>             }
> ```
> 
> where did these particle IDs come from? were they not the same for all of 1.7.10 - 1.18.1?

Afaik particle ids change quite frequently, it might be worth taking a look at ViaVersion's particle stuff: https://github.com/ViaVersion/ViaVersion
