### ISSUE TITLE
Unable to login 

### ISSUE THREAD

**Issue by EternalMC** [iceiix/stevenarella#392]
# Issue
The client allows me to enter a username/email but it won't allow me to enter a password.
## Comments
Is this feature not complete if so is there any way around it?

**Comment by skillman623** [comment]
Okay so I have a few questions if you don't mind:

- What OS are you on?
Are you running a prebuilt image or did you compile it yourself?
Is your password just a series of asterisks ' ******** '?

I just did a fresh compile on Windows 10 and it seems to work. I can test on windows 8 or Linux if you need me to.

**Comment by EternalMC** [comment]
OS: Win 10
I compiled it 
No I can't even click to select the password.
Specs:
r7 3700x
gtx 1050ti

**Comment by ColdIce1605** [comment]
@skillman623 
got any ideas?

**Comment by skillman623** [comment]
I'm kind of out of ideas here. Some more generic things that you could try are:

- Recompile- open a terminal in the Stevenarella directory and do `cargo clean` then `cargo build`
- Change the OPT level and rebuild- the easiest way to do this is to build it in release mode `cargo build --release` as this sets the opt level to 3. Alternatively this can be changed from the Cargo.toml file.

**Comment by PureTryOut** [comment]
Note that I can't _click_ on the password field either (which should be fixed), but I can enter the field by pressing tab.

**Comment by EternalMC** [comment]
Oof got in but now the 0x23 16 bytes left error happens

**Comment by skillman623** [comment]
Could you please post the full error message @EternalMC ? I'm unable to recreate the panic.

Also could you please rename this issue for clarity, perhaps something like "Unable to select password box on login screen".

**Comment by EternalMC** [comment]
I'll close this one and create a new one for it.
