### ISSUE TITLE
1.16.1: EntityEquipment_VarInt : Main thread panic: Failed to read all of packet 0x47, had 363 bytes left - enchants

### ISSUE THREAD

**Issue by Protonull** [iceiix/stevenarella#408]
Compiled from most recent commit: 7869893038a4b5699f180ba6afa84bd1e29cc1f0

When connecting to a 1.16.1 server with no other procotols supported, it almost instantly panics when loading the world.

Packet: 0x47 ([Clientbound - Entity Equipment](https://wiki.vg/Protocol#Entity_Equipment))

Executed with: `stevenarella.exe --network-debug --default-protocol-version 736`

```
[protocol/mod.rs:1122][DEBUG] Decompressed threshold=256 len=233 uncompressed_size=424 to 424 bytes
[protocol/mod.rs:1141][DEBUG] about to parse id=47, dir=Clientbound state=Play
[protocol/mod.rs:1151][DEBUG] packet = Some(EntityEquipment_VarInt(EntityEquipment_VarInt { entity_id: 53, slot: 128, item: Some(Stack { id: 7, count: 1, damage: None, tag: Some(NamedTag("", Compound({"Charged": Byte(0), "Damage": Int(29), "ChargedProjectiles": List([])}))) }) }))
thread 'main' panicked at 'Err: Err("Failed to read all of packet 0x47, had 363 bytes left")', src\server\mod.rs:571:33
stack backtrace:
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: <unknown>
  14: <unknown>
  15: <unknown>
  16: <unknown>
  17: <unknown>
  18: <unknown>
  19: <unknown>
  20: BaseThreadInitThunk
  21: RtlUserThreadStart
```

Not sure how to get a full stack trace though since I'm not familiar with Rust.

**Comment by iceiix** [comment]
@Protonull can you attach the output of `last-packet`? (thanks for running with --network-debug!)

**Comment by theLMGN** [comment]
@iceiix not op, but same rror
```
 ~  set RUST_BACKTRACE full; /Users/thelmgn/Downloads/stevenarella-macos-latest --network-debug > /dev/null                                                                                                         Wed  4 Nov 18:59:00 2020
thread 'main' panicked at 'Err: Err("Failed to read all of packet 0x47, had 363 bytes left")', src/server/mod.rs:571:33
stack backtrace:
   0: _rust_begin_unwind
   1: std::panicking::begin_panic_fmt
   2: stevenarella::server::Server::entity_tick
   3: stevenarella::server::Server::tick
   4: stevenarella::main2::{{closure}}
   5: <winit::platform_impl::platform::app_state::EventLoopHandler<T> as winit::platform_impl::platform::app_state::EventHandler>::handle_nonuser_event
   6: winit::platform_impl::platform::app_state::Handler::handle_nonuser_event
   7: winit::platform_impl::platform::app_state::AppState::cleared
   8: ____CFXPCCreateCFObjectFromXPCObject_block_invoke
   9: ___CFRunLoopObserverCancel
  10: ___CFRunLoopRun
  11: ___CFTSRToDispatchTime
  12: _RunCurrentEventLoopInMode
  13: _ReceiveNextEventCommon
  14: __BlockUntilNextEventMatchingListInModeWithFilter
  15: __DPSNextEvent
  16: -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:]
  17: -[NSApplication run]
  18: winit::platform_impl::platform::event_loop::EventLoop<T>::run
  19: winit::event_loop::EventLoop<T>::run
  20: stevenarella::main2
  21: stevenarella::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
 !  ~  cat last-packet                                                                                                                                                                                    4863ms  Wed  4 Nov 18:59:06 2020
����

RepairCost
                Enchantments
idminecraft:depth_striderlvlDamage��

RepairCost
                Enchantments
idminecraft:blast_protectionlvlDamage��

RepairCost
                Enchantments
idminecraft:mendinglvidminecraft:protectionlvlDamage�

RepairCost
                Enchantments
idminecraft:aqua_affinitylvidminecraft:protectionlvlDamage⏎
 ~                                                                                                                                                                                                                  Wed  4 Nov 18:59:09 2020





```

**Comment by iceiix** [comment]
Saving hex dump of http://lmgn.uk/UGz.last-packet here:

```
00000000  c7 00 88 01 82 01 85 05  01 0a 00 00 03 00 0a 52  |...............R|
00000010  65 70 61 69 72 43 6f 73  74 00 00 00 01 09 00 0c  |epairCost.......|
00000020  45 6e 63 68 61 6e 74 6d  65 6e 74 73 0a 00 00 00  |Enchantments....|
00000030  01 08 00 02 69 64 00 17  6d 69 6e 65 63 72 61 66  |....id..minecraf|
00000040  74 3a 64 65 70 74 68 5f  73 74 72 69 64 65 72 02  |t:depth_strider.|
00000050  00 03 6c 76 6c 00 03 00  03 00 06 44 61 6d 61 67  |..lvl......Damag|
00000060  65 00 00 00 00 00 83 01  84 05 01 0a 00 00 03 00  |e...............|
00000070  0a 52 65 70 61 69 72 43  6f 73 74 00 00 00 01 09  |.RepairCost.....|
00000080  00 0c 45 6e 63 68 61 6e  74 6d 65 6e 74 73 0a 00  |..Enchantments..|
00000090  00 00 01 08 00 02 69 64  00 1a 6d 69 6e 65 63 72  |......id..minecr|
000000a0  61 66 74 3a 62 6c 61 73  74 5f 70 72 6f 74 65 63  |aft:blast_protec|
000000b0  74 69 6f 6e 02 00 03 6c  76 6c 00 04 00 03 00 06  |tion...lvl......|
000000c0  44 61 6d 61 67 65 00 00  00 00 00 84 01 83 05 01  |Damage..........|
000000d0  0a 00 00 03 00 0a 52 65  70 61 69 72 43 6f 73 74  |......RepairCost|
000000e0  00 00 00 03 09 00 0c 45  6e 63 68 61 6e 74 6d 65  |.......Enchantme|
000000f0  6e 74 73 0a 00 00 00 02  08 00 02 69 64 00 11 6d  |nts........id..m|
00000100  69 6e 65 63 72 61 66 74  3a 6d 65 6e 64 69 6e 67  |inecraft:mending|
00000110  02 00 03 6c 76 6c 00 01  00 08 00 02 69 64 00 14  |...lvl......id..|
00000120  6d 69 6e 65 63 72 61 66  74 3a 70 72 6f 74 65 63  |minecraft:protec|
00000130  74 69 6f 6e 02 00 03 6c  76 6c 00 04 00 03 00 06  |tion...lvl......|
00000140  44 61 6d 61 67 65 00 00  00 00 00 05 01 82 05 01  |Damage..........|
00000150  0a 00 00 03 00 0a 52 65  70 61 69 72 43 6f 73 74  |......RepairCost|
00000160  00 00 00 03 09 00 0c 45  6e 63 68 61 6e 74 6d 65  |.......Enchantme|
00000170  6e 74 73 0a 00 00 00 02  08 00 02 69 64 00 17 6d  |nts........id..m|
00000180  69 6e 65 63 72 61 66 74  3a 61 71 75 61 5f 61 66  |inecraft:aqua_af|
00000190  66 69 6e 69 74 79 02 00  03 6c 76 6c 00 01 00 08  |finity...lvl....|
000001a0  00 02 69 64 00 14 6d 69  6e 65 63 72 61 66 74 3a  |..id..minecraft:|
000001b0  70 72 6f 74 65 63 74 69  6f 6e 02 00 03 6c 76 6c  |protection...lvl|
000001c0  00 04 00 03 00 06 44 61  6d 61 67 65 00 00 00 00  |......Damage....|
000001d0  00                                                |.|
```

**Comment by iceiix** [comment]
Testing with https://github.com/iceiix/stevenarella/pull/438, the packet parses without error:

```
cargo run  -- -N ~/Downloads/UGz.last-packet -p 736

about to parse id=47, dir=Clientbound state=Play
packet = Some(EntityEquipment_VarInt(EntityEquipment_VarInt { entity_id: 136, slot: 130, item: Some(Stack { id: 5, count: 1, damage: None, tag: Some(NamedTag("", Compound({"Enchantments": List([Compound({"id": String("minecraft:depth_strider"), "lvl": Short(3)})]), "Damage": Int(0), "RepairCost": Int(1)}))) }) }))
```

**Comment by iceiix** [comment]
1.16 changed slot/item to an array of slot/item (v1_16_1, v1_16_4+):

https://wiki.vg/index.php?title=Pre-release_protocol&oldid=15895
https://wiki.vg/index.php?title=Pre-release_protocol&oldid=15878

<img width="815" alt="Screen Shot 2020-12-19 at 1 43 27 PM" src="https://user-images.githubusercontent.com/43691553/102700193-2e59c380-4200-11eb-85d3-27e425b4aece.png">


1.15.2 (v1_15) only had one slot/item, no array: https://wiki.vg/index.php?title=Protocol&oldid=16067#Entity_Equipment

<img width="583" alt="Screen Shot 2020-12-19 at 1 45 14 PM" src="https://user-images.githubusercontent.com/43691553/102700231-6eb94180-4200-11eb-8027-5c1b0f9c1495.png">

**Comment by iceiix** [comment]
Implemented the EntityEquipment_Array packet variant in #438, which was important, but it turns out this packet only has one array element, so there is another bug here.

packet = Some(EntityEquipment_Array(EntityEquipment_Array { entity_id: 136, equipments: EntityEquipments { equipments: [EntityEquipment { slot: 2, item: Some(Stack { id: 645, count: 1, damage: None, tag: Some(NamedTag("", Compound({"Damage": Int(0), "RepairCost": Int(1), "Enchantments": List([Compound({"id": String("minecraft:depth_strider"), "lvl": Short(3)})])}))) }) }] } }))

pos = 102
Failed to read all of packet 0x47, had 363 bytes left

The extra unparsed bytes:

'\x83\x01\x84\x05\x01\n\x00\x00\x03\x00\nRepairCost\x00\x00\x00\x01\t\x00\x0cEnchantments\n\x00\x00\x00\x01\x08\x00\x02id\x00\x1aminecraft:blast_protection\x02\x00\x03lvl\x00\x04\x00\x03\x00\x06Damage\x00\x00\x00\x00\x00\x84\x01\x83\x05\x01\n\x00\x00\x03\x00\nRepairCost\x00\x00\x00\x03\t\x00\x0cEnchantments\n\x00\x00\x00\x02\x08\x00\x02id\x00\x11minecraft:mending\x02\x00\x03lvl\x00\x01\x00\x08\x00\x02id\x00\x14minecraft:protection\x02\x00\x03lvl\x00\x04\x00\x03\x00\x06Damage\x00\x00\x00\x00\x00\x05\x01\x82\x05\x01\n\x00\x00\x03\x00\nRepairCost\x00\x00\x00\x03\t\x00\x0cEnchantments\n\x00\x00\x00\x02\x08\x00\x02id\x00\x17minecraft:aqua_affinity\x02\x00\x03lvl\x00\x01\x00\x08\x00\x02id\x00\x14minecraft:protection\x02\x00\x03lvl\x00\x04\x00\x03\x00\x06Damage\x00\x00\x00\x00\x00'

the parsed bytes:

'\xc7\x00\x88\x01\x82\x01\x85\x05\x01\n\x00\x00\x03\x00\nRepairCost\x00\x00\x00\x01\t\x00\x0cEnchantments\n\x00\x00\x00\x01\x08\x00\x02id\x00\x17minecraft:depth_strider\x02\x00\x03lvl\x00\x03\x00\x03\x00\x06Damage\x00\x00\x00\x00\x00'

The enchantments `"Enchantments": List([Compound({"id": String("minecraft:depth_strider"), "lvl": Short(3)`` is only the first enchantment (Depth Strider III), it parses up to Damage: 0, then stops parsing. https://wiki.vg/NBT

NBT parsing bug

**Comment by iceiix** [comment]
Now parses correctly with changes in #438 (it was the equipment array):

packet = Some(EntityEquipment_Array(EntityEquipment_Array { entity_id: 136, equipments: EntityEquipments { equipments: [EntityEquipment { slot: 2, item: Some(Stack { id: 645, count: 1, damage: None, tag: Some(NamedTag("", Compound({"Damage": Int(0), "RepairCost": Int(1), "Enchantments": List([Compound({"lvl": Short(3), "id": String("minecraft:depth_strider")})])}))) }) }, EntityEquipment { slot: 3, item: Some(Stack { id: 644, count: 1, damage: None, tag: Some(NamedTag("", Compound({"RepairCost": Int(1), "Enchantments": List([Compound({"lvl": Short(4), "id": String("minecraft:blast_protection")})]), "Damage": Int(0)}))) }) }, EntityEquipment { slot: 4, item: Some(Stack { id: 643, count: 1, damage: None, tag: Some(NamedTag("", Compound({"RepairCost": Int(3), "Enchantments": List([Compound({"id": String("minecraft:mending"), "lvl": Short(1)}), Compound({"id": String("minecraft:protection"), "lvl": Short(4)})]), "Damage": Int(0)}))) }) }, EntityEquipment { slot: 5, item: Some(Stack { id: 642, count: 1, damage: None, tag: Some(NamedTag("", Compound({"RepairCost": Int(3), "Enchantments": List([Compound({"lvl": Short(1), "id": String("minecraft:aqua_affinity")}), Compound({"lvl": Short(4), "id": String("minecraft:protection")})]), "Damage": Int(0)}))) }) }] } }))
