### ISSUE TITLE
UI: Text boxes can't be clicked

### ISSUE THREAD

**Issue by skillman623** [iceiix/stevenarella#415]
On the main menu the text boxes can't be clicked.
This affects the login page **username** and **password** boxes as well as the server selection **IP** and **server name** boxes.
Text boxes should be clickable and usable by the arrow keys instead of tab only navigation as it is now.

Secondary issue from #392

**Comment by iceiix** [comment]
Confirmed, this seems to be a missing feature in src/ui/mod.rs TextBoxRef. Handle click_at?

**Comment by iceiix** [comment]
This change sort of works:

```diff
diff --git a/src/ui/mod.rs b/src/ui/mod.rs
index c3df9bd..3357327 100644
--- a/src/ui/mod.rs
+++ b/src/ui/mod.rs
@@ -1615,6 +1615,11 @@ impl UIElement for TextBox {
                 .alignment(VAttach::Middle, HAttach::Left)
                 .attach(&mut *textbox),
         );
+
+        textbox.add_click_func(|x, _game| {
+            x.focused = true;
+            true
+        });
     }
 }
```

it focuses the clicked text box, but there is a problem: it doesn't unfocus the other elements. src/ui/mod.rs impl Element has is_focused() and set_focused(), and impl Container has add_focusable(), focusable_elements `Vec<WeakElement>`, focusables `Vec<Element>`, and cycle_focus() (called on VirtualKeyCode::Tab) to manage focusing.
