### ISSUE TITLE
Glutin/winit: Buttons dont align with mouse

### ISSUE THREAD

**Issue by a8underscore** [iceiix/stevenarella#419]
Im not sure what info to give, so If i miss something please let me know
```
Operating System: Manjaro Linux
KDE Plasma Version: 5.19.5
KDE Frameworks Version: 5.74.0
Qt Version: 5.15.1
Kernel Version: 5.9.1-1-MANJARO
OS Type: 64-bit
Processors: 4 × Intel® Core™ i7-5650U CPU @ 2.20GHz
Memory: 7.7 GiB of RAM
Graphics Processor: Mesa Intel® HD Graphics 6000
```

I tried the precompiled binary and I also tried complieing with rust cargo, both same issue

here is video of problem
https://streamable.com/kk1nhh

**Comment by iceiix** [comment]
<img width="1248" alt="Screen Shot 2020-11-01 at 5 01 57 PM" src="https://user-images.githubusercontent.com/43691553/97820707-43848e00-1c64-11eb-9da5-6d9f7fc53976.png">

Thanks for the report. I have seen similar mouse tracking problems when updating glutin/winit (https://github.com/iceiix/stevenarella/pull/334), this configuration is a useful datapoint. Curious if #334 fixes the problem in your configuration (but breaks it in mine, and reportedly on Linux with X11).

@a8underscore some additional info, do you know if Manjaro Linux is using X11? or an alternative like Wayland? Also do you happen to have a HiDPI display? (2x, etc.)

**Comment by a8underscore** [comment]
I am on X11.
I do not have a HiDPI display

**Comment by iceiix** [comment]
@a8underscore I believe this should be fixed by https://github.com/iceiix/stevenarella/pull/334 can you confirm, or does it still occur in the latest build
