### ISSUE TITLE
Question: How alive is the project? (Does contributing make sense?)

### ISSUE THREAD

**Issue by ZainlessBrombie** [iceiix/stevenarella#436]
Heyho!

as a plugin developer, server owner and general not-fond-of-microsoft rustacean, I was very annoyed with Microsofts move to make their Account mandatory.

Now I know the readme says "don't expect this to go anywhere", but I'd be willing to _try_ to get this project to a playable state (Mobs, graphics, quality of life, chat) if you say it is worth it and you think MS won't come swooping in with their lawyers.  
Edit: None of this would be commercial use so I guess it is okay, right?

There would be a few things I would need / want to add, apart from MC features though:  
1) Optionally using no account. Meaning it can't use the default texture pack by itself, unless locally available.  
2) Optionaly using a "stevenarella" - account. This would be an account which is free but _can_ be paid for incrementally ("investment"). Money could go to charity, whatever. Servers with which the client authorizes using a stevenarella account could set a minimum account investment. The point is that griefers are less of a problem if you can ban their paid-for-accounts. Minecraft accounts would be considered investment of 20 (?; €/$?), with the ability to link to a stevenarella account once and add that investment to it.

Curious what you think! :)

**Comment by Kezii** [comment]
I think that if you want a drop-in replacement for minecraft, you should probably look to minetest, they have an actual game with working modding and and community

BTW, stevenarella already works without microsoft account, making a stevenarella account doesn't really make sense and it's probably illegal

**Comment by Kezii** [comment]
And yes, contributing makes sense, it's the only source of "minecraft primitives" that we have in rust, I used the protocol library for one of my experiments, and with all its kinks, it worked

If it wasn't for this I had to do everything in java, so thanks iceiix :P

**Comment by ZainlessBrombie** [comment]
Mmh... that one's in C++ and the idea is that both standard clients and stevenarella/offline clients could connect. But I would need a way to prevent spamming griefer accounts...

Why do you think a stevenarella account would be illegal? After all, we are not using anything MS made, right? :)

Huh maybe I'd be better off using feather? My plugin uses next to no vanilla features anyways :thinking:
