### ISSUE TITLE
feather: panic unwrapping None at src/server/mod.rs:1744:45, entity::player::PlayerModel self.player.unwrap()

### ISSUE THREAD

**Issue by iceiix** [iceiix/stevenarella#465]
Connecting to a feather server, https://github.com/feather-rs/feather build from source 9539a21, crashes:

```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/server/mod.rs:1744:45
```

in src/server/mod.rs on_player_info(), while unwrapping self.player:

```rust
                    // Refresh our own skin when the server sends it to us.
                    // The join game packet can come before this packet meaning
                    // we may not have the skin in time for spawning ourselves.
                    // This isn't an issue for other players because this packet
                    // must come before the spawn player packet.
                    if info.uuid == self.uuid {
                        let model = self
                            .entities
                            .get_component_mut_direct::<entity::player::PlayerModel>(
                                self.player.unwrap(), // *** <-- crash here
                            )
                            .unwrap();
                        model.set_skin(info.skin_url.clone());
```

self.player is set in `on_game_join`: `self.player = Some(player);`, so on_player_info could have been received before on_game_join?

**Comment by Supermath101** [comment]
By the way, feather is currently going through a massive rewrite under the [1.16 brach](https://github.com/feather-rs/feather/tree/1.16), (see: [GH pull request #307](https://github.com/feather-rs/feather/pull/307) and [GH issue #341](https://github.com/feather-rs/feather/issues/341)).

**Comment by caelunshun** [comment]
Feather now sends the `PlayerInfo` packet after `JoinGame` on the 1.16 branch (feather-rs/feather#307). Testing Steverarella (latest git) with Feather 1.16 gives me a new panic:
```
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: "RSA error: message representative out of range"', src/server/mod.rs:203:80
```

**Comment by iceiix** [comment]
Interesting new error! src/server/mod.rs:203 is:

```rust
        let shared_e = rsa_public_encrypt_pkcs1::encrypt(&public_key, &shared).unwrap();
```

this is from my other module (a quick-and-dirty RSA encryption library to replace the more heavyweight OpenSSL dependency I wanted to get rid of, but couldn't find a similarly lightweight Rust library replacement - maybe there is one now): https://github.com/iceiix/rsa_public_encrypt_pkcs1/blob/master/src/lib.rs#L110

where I added this check based on [RFC8017](https://tools.ietf.org/html/rfc8017#section-5.1.1):

```rust
    // https://tools.ietf.org/html/rfc8017#section-5.1.1
    /* 1.  If the message representative m is not between 0 and n - 1,
     *     output "message representative out of range" and stop.
     */
    if m.sign() != num::bigint::Sign::Plus || m > n - 1 {
        return Err("RSA error: message representative out of range".to_string());
    }
```

I wonder which condition is failing (m is negative, or greater than n - 1?)

**Comment by iceiix** [comment]
Since the PlayerModel error no longer occurs, I'll close this issue, but use this newer issue for the (mysterious) RSA error: https://github.com/iceiix/stevenarella/issues/507 feather: RSA Issue "RSA error: message representative out of range"', src\server\mod.rs:203:80
