### ISSUE TITLE
Is ThreadRng cryptographically secure enough?

### ISSUE THREAD

**Issue by ColdIce1605** [iceiix/stevenarella#508]
https://github.com/rust-random/rand/issues/463

I think this issue solves that // Todo in src/server/mod.rs

**Comment by iceiix** [comment]
Referring to https://github.com/iceiix/stevenarella/blob/master/src/server/mod.rs#L200-L201 

```rust
        let mut shared = [0; 16];
        // TODO: is this cryptographically secure enough?
        rand::thread_rng().fill(&mut shared);
```

from the rand issue:

> And an important note on security: we should aim to provide a secure source of random data, but ultimately it is up to users to decide how much they trust our implementation and what their risks are. thread_rng does not have the simplest code to review and is currently young and subject to further change. Also we may or may not implement forward secrecy (backtracking resistance), and for ultimate security solutions using no local state may be preferred.

which is closed, so I think you're the answer to the comment is "yes" - I should remove the comment
