### ISSUE TITLE
Transparent window

### ISSUE THREAD

**Issue by terrarier2111** [iceiix/stevenarella#570]
When starting stevenrella, it appears transparent
![Bildschirmfoto vom 2021-07-04 16-28-22](https://user-images.githubusercontent.com/58695553/124388833-e5bdaf80-dce4-11eb-871b-abe0e5b972b2.png)

**Comment by iceiix** [comment]
Weird, I haven't seen this. The different sizes of the UI elements is also unexpected. @terrarier2111 what OS is this on, and what video card?

**Comment by terrarier2111** [comment]
OS: Fedora 34
GPU: AMD ATI Radeon RX 5600 OEM/5600 XT /

Btw the gui elements had the same size, but i had a 'real' mc window in the background which can be seen cuz the stevenrella window is transparent.

**Comment by PureTryOut** [comment]
I can reproduce this on Alpine Linux (edge) with a AMD RX580.

**Comment by terrarier2111** [comment]
> I can reproduce this on Alpine Linux (edge) with a AMD RX580.
> 
> **EDIT:** And I found the cause: Wayland. On KDE Plasma with the Wayland session I get a transparent window, but on X11 on the same machine I don't. @terrarier2111 uses Fedora 34 which afaik defaults to GNOME also on Wayland, so that's probably the cause here.

Could you try if you can reproduce this with my pr?
