### ISSUE TITLE
Cannot add steven_protocol as a dependency

### ISSUE THREAD

**Issue by kory33** [iceiix/stevenarella#587]
Hello, I tried using `steven_protocol` module for my own development by adding

```toml
[dependencies]
steven_protocol = { git = "https://github.com/iceiix/stevenarella", rev = "1a9e8d40" }
```

to the `Cargo.toml`.

However, this resulted in an error saying

```
C:\Users\Kory\CLionProjects\playground> cargo install --path .
  Installing playground v0.1.0 (C:\Users\Kory\CLionProjects\playground)
    Updating git repository `https://github.com/iceiix/stevenarella`
    Updating crates.io index
error: failed to compile `playground v0.1.0 (C:\Users\Kory\CLionProjects\playground)`, intermediate artifacts can be found at `C:\Users\Kory\CLionProjects\playground\target`

Caused by:
  failed to select a version for the requirement `aesni = "^0.7"`
  candidate versions found which didn't match: 0.99.99, 0.10.0, 0.9.0, ...
  location searched: crates.io index
  required by package `aes v0.4.0`
      ... which is depended on by `steven_protocol v0.0.1 (https://github.com/iceiix/stevenarella?rev=1a9e8d40#1a9e8d40)`
      ... which is depended on by `playground v0.1.0 (C:\Users\Kory\CLionProjects\playground)`
```

The [version 0.7.0 of aesni](https://crates.io/crates/aesni/0.7.0) has been yanked, so I believe `steven_protocol` has to upgrade the version of `aes` dependency.

**Comment by kory33** [comment]
Looks like [simply updating `aes` and `cfb8` to 0.5.0](https://github.com/kory33/stevenarella/commit/31f56ffc1f21d78fe8a50e8a91d6448e06a3e1fc) would fix this issue. However, updating them any more than this leads to an error due to some change in `cfb8`.

**Comment by iceiix** [comment]
Hmm, I should update the protocol/Cargo.toml (and other subproject) dependencies, dependabot doesn't seem to catch these new versions in subprojects :(

**Comment by iceiix** [comment]
@kory33 Updated aes & cfb to latest, and other protocol crate deps, in #590, can you check if this fixes the problem for you

**Comment by kory33** [comment]
@iceiix awesome, I can confirm that cargo no longer complains after the change!
