### ISSUE TITLE
Clipboard pasting does not work on Wayland

### ISSUE THREAD

**Issue by PureTryOut** [iceiix/stevenarella#597]
I have a password that's very hard to type so I always copy it from my password manager, but that doesn't work on Wayland sadly. On X11 however this works fine.

**Comment by iceiix** [comment]
Using the [clipboard](https://lib.rs/crates/clipboard) crate https://github.com/aweinstock314/rust-clipboard which supports various clipboards, including X11, but not Wayland. Looking at their repo, there is an open pull request to add Wayland: https://github.com/aweinstock314/rust-clipboard/pull/64 - from 2019 - project inactive? The comments mention an alternate implementation: https://github.com/chrisduerr/rust-clipboard. And there's another different open pull request for wl-clipboard-rs https://github.com/aweinstock314/rust-clipboard/pull/65 but:

> …it seems like this repo may have been abandoned, so I'm not sure what the best path forward is. I would love to see this make it back into crates.io

Their feature request issue is https://github.com/aweinstock314/rust-clipboard/issues/34

I guess we could try to switch to one of the forks with Wayland support (or find an actively maintained alternative clipboard crate, if there is one)

**Comment by nyvs** [comment]
I use wayland, for me it does work actually

**Comment by servusdei2018** [comment]
I use Wayland  too and pasting works just fine. @PureTryOut can you confirm you're still having this issue?

**Comment by PureTryOut** [comment]
I don't use Stevenarella anymore but Leafish instead. If it works for you guys I'd consider it fixed.
