### ISSUE TITLE
cargo install rebuilds after cargo build

### ISSUE THREAD

**Issue by txtsd** [iceiix/stevenarella#664]
So I run `cargo build --release` and then `cargo install --path .` thinking the install task will have significantly less work to do, however it rebuilds the entire codebase all over again.

What's the correct way to build and then install?

**Comment by iceiix** [comment]
@txtsd I believe you can just run `cargo install`, it will build automatically before installation. But I found this cargo issue: https://github.com/rust-lang/cargo/issues/5667 cargo-install unnecessarily rebuilds everything
