### ISSUE TITLE
Publish binary releases

### ISSUE THREAD

**Issue by iceiix** [iceiix/stevenarella#93]
This looks useful: https://github.com/japaric/trust

> Travis CI and AppVeyor template to test your Rust crate on 5 architectures and publish binary releases of it for Linux, macOS and Windows

**Comment by MCOfficer** [comment]
i have some experience with CIs and might give this a try. Are you still working on steven?

**Comment by iceiix** [comment]
@MCOfficer yes would definitely be interested in help with this if you get a chance. Working on this project intermittently when I can…

**Comment by iceiix** [comment]
Azure Pipelines (#346) might help with this. Builds on Linux, macOS, and Windows. 

Pipeline artifacts? https://docs.microsoft.com/en-us/azure/devops/pipelines/artifacts/pipeline-artifacts?view=azure-devops&tabs=yaml

**Comment by SuperSandro2000** [comment]
I would prefer it if releases are still published on github trough the releases feature.

**Comment by iceiix** [comment]
Looks like that should be possible with https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/github-release?view=azure-devops

**Comment by MCOfficer** [comment]
Oh, i did lose track of this... Should i still do it? I have no experience with azure pipes, so it would come down to an actions-based solution.

See for example <https://github.com/EndlessSkyCommunity/ESLauncher2/releases>, <https://github.com/brandad-systems/container-stats/releases>
